import {newLessons, microScenes} from './chapters.js';
import {createExpansion} from './expansion.js';
let expansion;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const lessons=[
{nav:'The big picture',title:'A model learns patterns.<br>Then creates something new.',tag:'OVERVIEW',intro:'Generative AI learns statistical structure from examples, then uses that structure to create text, images, audio or other content. Here, follow a language model as it learns to predict the next token.',key:'Two different journeys',take:'Training adjusts billions of numerical weights. Inference uses those weights to generate a response to a new prompt.',lab:'overview',deep:'What does “learning” mean?',body:'A model starts with numerical parameters, usually initialized randomly. Repeated predictions, feedback and updates make useful patterns more likely. Its weights encode distributed patterns, not a searchable folder of all its examples. Memorization can still happen. Fluent output can be mistaken, so prediction is not a guarantee of truth.',extra:'The scope of this atlas',more:'The map follows a typical decoder-only Transformer language model. Generative AI also includes diffusion, autoregressive audio and other architectures. Multimodal models use additional encoders or token representations for images, video and sound. The geometry here is a teaching diagram, not the physical shape of AI.'},
{nav:'Training data',title:'First, prepare<br>the examples.',tag:'DATA',intro:'Text, code and other permitted content are collected, cleaned, filtered and deduplicated. The resulting examples are split into training and held-out sets, then encoded into sequences of tokens.',key:'The data comes first',take:'Embeddings, attention and backpropagation do not turn into training data. They are mechanisms for learning from prepared examples.',lab:'data',deep:'Where do the labels come from?',body:'For next-token pretraining, each sequence supplies its own targets: input “The sky is” teaches the model to predict the next token from the source text. Shifting a sequence by one position provides targets at many positions. A causal mask prevents looking ahead. This is called self-supervised learning.',extra:'How this scales to frontier models',more:'Large training pipelines blend datasets, remove duplicates, filter low-quality content, respect permissions and privacy requirements, and check evaluation contamination. Documents are tokenized, packed into context windows and streamed as batches. Held-out examples measure generalization. Synthetic examples may be added after quality checks; there is no universal recipe or public specification for every frontier model.'},
{nav:'Tokenization',title:'Turn text into<br>small, reusable pieces.',tag:'REPRESENTATION',intro:'A tokenizer maps text to a sequence of discrete IDs. A token may be a word, part of a word, punctuation or bytes. The same tokenizer is used when preparing training examples and reading a prompt.',key:'An ID is an address',take:'Token 17 is not “more meaningful” than token 16. IDs simply identify entries in a vocabulary.',lab:'tokens',deep:'Why not use only words?',body:'Subword tokenizers balance vocabulary size with the ability to encode unfamiliar words, code and many languages. Common approaches learn reusable pieces from a corpus. Spaces and capitalization can affect token boundaries. The little tokenizer here uses a fixed teaching vocabulary, not the tokenizer of a frontier model.',extra:'Sequences and context windows',more:'The context window limits how many tokens can be processed in one sequence. Special tokens can mark boundaries, roles or the end of a turn. Padding masks keep filler tokens from influencing attention and loss. Training batches often pack shorter examples to reduce wasted computation.'},
{nav:'Embeddings & vectors',title:'Give each token<br>a numerical representation.',tag:'REPRESENTATION',intro:'An embedding lookup replaces each token ID with a vector: an ordered list of numbers. Training adjusts this table so its representations become useful for prediction.',key:'A vector is a list of coordinates',take:'Real embeddings have many dimensions. This 3D view is a tiny, illustrative projection; its axes are not literal “meaning” categories.',lab:'vectors',deep:'From vectors to context',body:'The initial token embedding is usually fixed for a given token ID at inference. Transformer layers then create context-dependent hidden vectors: “bank” can be represented differently near “river” and “money.” Similarity is often measured by a dot product or cosine similarity, but similarity alone does not imply truth or identical meaning.',extra:'How does the model know the order?',more:'Attention alone does not encode sequence order. Positional information is added or incorporated into attention; rotary positional embeddings are one common approach. Training updates token embeddings alongside the rest of the model. A vector database is optional external retrieval infrastructure, not a required part of a Transformer.'},
{nav:'Inside a transformer',title:'A stack of layers<br>builds understanding in context.',tag:'MODEL',intro:'Each Transformer block combines attention, which mixes information between tokens, with a feed-forward network, which transforms each position’s representation. Many blocks repeat this process.',key:'The same weights, different inputs',take:'Every layer applies learned mathematical operations. Hidden vectors change during a forward pass; learned weights change only during training.',lab:'transformer',deep:'What is inside one block?',body:'A typical pre-normalized decoder block uses normalization → masked multi-head attention → residual addition → normalization → feed-forward network → residual addition. Residual paths help information and gradients travel through a deep model. Exact block designs differ across architectures.',extra:'From the last layer to a prediction',more:'The final hidden vectors are projected to vocabulary-sized logits. Softmax turns these scores into probabilities. Dense networks apply the feed-forward weights to every token. Mixture-of-experts models route tokens through selected expert networks. This atlas shows the dense case for clarity.'},
{nav:'Attention',title:'Which earlier tokens<br>matter right now?',tag:'MODEL',intro:'Attention lets a token gather relevant information from allowed positions. Queries ask what is needed, keys describe what each position offers, and values supply the information to mix.',key:'Looking back, never ahead',take:'In a causal language model, a position can attend to itself and earlier positions. Future tokens are masked out during training too.',lab:'attention',deep:'The actual operation',body:'Learned projections turn hidden vectors into Q (queries), K (keys) and V (values). Scaled query–key dot products are masked, normalized with softmax and used to form a weighted sum of values. Multiple heads learn different projections and their results are combined.',formula:'Attention(Q,K,V) = softmax(QKᵀ / √dₖ + mask)V',extra:'Attention is not an explanation of thought',more:'The matrix here contains invented weights to demonstrate the causal mask. Real attention changes with the input, layer and head. A high weight shows one information-routing relationship; it is not proof of what caused a model’s answer, nor evidence that the model understands a concept as a person would.'},
{nav:'Prediction & loss',title:'Make a prediction.<br>Measure the surprise.',tag:'TRAINING',intro:'During training, the model predicts a distribution over the next token. Loss measures how little probability it assigned to the correct target from the training example.',key:'Lower loss means better fit',take:'Assigning the actual next token more probability lowers cross-entropy loss. Held-out evaluation checks whether the improvement extends to unseen examples.',lab:'loss',deep:'One sequence, many predictions',body:'All known positions in a training sequence can be processed together with causal masking. Each position predicts its next token. Valid losses are averaged across positions and examples. The target token is withheld from the predicting position’s attention even though the whole sequence is available to the training system.',formula:'Loss for one target = −ln P(correct token)',extra:'What low loss does not tell you',more:'Low training loss alone does not establish factual accuracy, fairness, safety or reasoning reliability. Dataset quality, held-out loss and task-specific evaluations matter. Training loss need not decrease on every step because batches vary and optimization is noisy.'},
{nav:'Backpropagation',title:'Send feedback backward.<br>Adjust the weights.',tag:'TRAINING',intro:'Backpropagation applies the chain rule to compute how each trainable parameter contributed to the loss. An optimizer then uses those gradients to update the parameters.',key:'Gradients are directions of change',take:'The backward pass computes gradients. The optimizer performs the update. Repeat forward → loss → backward → update over many batches.',lab:'gradient',deep:'Follow one exact update',body:'The experiment uses a tiny model, ŷ = w × 2, with target 4. Its loss is (ŷ − 4)², so dL/dw = 4(2w − 4). A gradient-descent step subtracts learning rate × gradient from w. This is a real calculation for one parameter, not a simulation of a frontier model’s performance.',formula:'w_new = w − learning_rate × dL/dw',extra:'At frontier scale',more:'Automatic differentiation tracks forward operations and computes gradients through matrix products, attention and other layers. Optimizers such as AdamW also keep numerical state. Mixed precision, activation checkpointing and distributed optimizer state help manage memory and compute. Backpropagation creates gradients, not new text examples.'},
{nav:'GPUs & parallelism',title:'Millions of operations.<br>Working together.',tag:'COMPUTE',intro:'GPUs accelerate the matrix operations that dominate neural networks. Large training jobs spread examples, weight matrices and layers across many devices, with fast interconnects moving information between them.',key:'Parallel inside; sequential between tokens',take:'Training can process known token positions in parallel. Standard autoregressive inference must choose a new token before generating the next one.',lab:'gpu',deep:'Three ways to divide the work',body:'Data parallelism runs model replicas on different batches and synchronizes gradients. Tensor parallelism splits individual tensor operations across devices. Pipeline parallelism places different layers on different devices and schedules microbatches through them. Real systems combine these approaches; larger models can also use expert and context parallelism.',extra:'Why more GPUs is not linear speedup',more:'Memory holds weights, activations, gradients and optimizer state during training. Bandwidth and interconnect communication can bottleneck the job. In inference, weights and the key–value cache take memory; batching improves throughput but can affect latency. CPUs handle orchestration and data preparation, while storage and networking keep the accelerators fed.'},
{nav:'Post-training',title:'From predicting text<br>to a useful assistant.',tag:'REFINEMENT',intro:'A pretrained model has learned broad patterns. Post-training can refine instruction following, conversational behavior and other capabilities using curated demonstrations, preferences and reward signals.',key:'The model still learns by updates',take:'Supervised fine-tuning and preference or reinforcement learning methods can change weights. Evaluations check the resulting behavior before deployment.',lab:'post',deep:'Different kinds of learning signals',body:'Supervised fine-tuning learns from prompt–response demonstrations. Preference methods use comparisons between candidate responses. Reinforcement learning can use reward models or checkable outcomes, such as whether code passes tests. These are distinct objectives; not every model follows the same sequence.',extra:'What gets deployed?',more:'A checkpoint contains learned weights and related model configuration. A serving system also needs the tokenizer, inference software and sufficient hardware. Applications may add system instructions, tools, retrieval and safeguards around the model. Those components are useful, but they are not all encoded in the weights.'},
{nav:'Inference',title:'A prompt goes in.<br>One token comes out.',tag:'GENERATION',intro:'The serving system tokenizes your prompt, embeds it and runs it through the trained layers. The final position produces a probability distribution for the next token. Decoding selects a token and appends it.',key:'Weights stay fixed in ordinary inference',take:'A prompt changes activations and context, not the model’s trained weights. Remembering a message in a conversation is different from retraining.',lab:'inference',deep:'Prefill and decode',body:'Prefill processes the known prompt tokens in parallel and builds the attention key–value cache. During decode, each new token reuses that cache rather than recalculating all earlier keys and values. The cache grows with context and consumes device memory.',extra:'Why answers can differ',more:'Temperature rescales logits before sampling. Lower values concentrate probability on higher-scoring tokens; higher values spread it out. Greedy decoding chooses the largest logit. Top-k and top-p can restrict candidates. Sampling probabilities describe what the model might say next, not whether a statement is true.'},
{nav:'The complete loop',title:'Now connect<br>the whole system.',tag:'PUT IT TOGETHER',intro:'Prepared examples train the model. Tokens become vectors; Transformer layers compute predictions; loss and gradients guide weight updates on GPUs. The trained model can then serve new requests.',key:'Two loops, one learned model',take:'Training: predict → score → differentiate → update. Inference: read context → predict → select → append → repeat.',lab:'complete',deep:'Is every conversation new training data?',body:'No. Ordinary inference does not automatically update weights. Whether a service retains conversations or later uses them in a separate training pipeline depends on its policies and settings. New data must be selected and prepared before it contributes to a later training run.',extra:'Beyond the model itself',more:'Retrieval can supply current documents within a prompt. Tools can perform calculations or external actions. Neither requires changing model weights during the conversation. Multimodal generative models represent non-text inputs differently, and diffusion models generate by iterative denoising rather than this exact next-token loop.'}
];
lessons.splice(11,0,...newLessons);
let current=0,mode='all',playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,angle=-.38,tilt=.61,zoom=1,targetZoom=1,focus=[0,0,0],targetFocus=[0,0,0],tick=0;
let trainW=.2,history=[12.96],trainStep=0,layer=2,attnRow=3,gpuCount=4,parallel='data',genTokens=[],temp=.8;
const col=['#82e5b5','#82e5b5','#82e5b5','#82e5b5','#b6a3ff','#b6a3ff','#b6a3ff','#b6a3ff','#82bfff','#b6a3ff','#f3bd71','#f3bd71'];
const pos=[[0,0,0],[-8,0,1],[-5,0,1],[-3,1,-3],[0,1,0],[0,1,0],[3.6,0,-3],[.2,0,-5],[0,-2.7,2.3],[4,0,.5],[7,0,3],[7,0,3]];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function labHTML(kind){switch(kind){
case'overview':return '<h3>Two paths through the same model</h3><div class="flow-list"><div>Learn from examples <em>TRAINING</em></div><div>Save the learned weights <em>CHECKPOINT</em></div><div>Generate from a prompt <em>INFERENCE</em></div></div><p>Choose a chapter, or click a structure in the 3D map. Use the controls to inspect the full system.</p><button class="primary" data-go="1">Follow a training example →</button><button class="secondary" data-go="11">Open reinforcement learning →</button><button class="secondary" data-go="15">Open agent loops →</button><button class="secondary" data-go="16">Open graphs & GraphRAG →</button>';
case'data':return '<h3>From a document to learning targets</h3><label for="dataExample">Choose a training example</label><select id="dataExample"><option>The sky is blue</option><option>A cat drinks milk</option><option>Water freezes into ice</option></select><div id="dataPairs"></div><p>Each prefix predicts the following word in this simplified word-level example. Actual batches use tokenizer IDs.</p>';
case'tokens':return '<h3>Try a teaching tokenizer</h3><label for="tokenInput">Your text (up to 120 characters)</label><input id="tokenInput" type="text" maxlength="120" value="Generative AI learns patterns."><div class="tokens" id="tokenOutput"></div><p id="tokenCount"></p><p>Spaces appear as ␠. Common pieces use a tiny fixed vocabulary; other characters fall back to Unicode-based IDs. Real tokenizers split differently.</p>';
case'vectors':return '<h3>Compare two toy vectors</h3><label for="vectorWord">Compare “cat” with</label><select id="vectorWord"><option value="kitten">kitten</option><option value="dog">dog</option><option value="car">car</option></select><canvas id="vectorCanvas" class="mini-canvas" width="550" height="330" aria-label="Three dimensional toy vector comparison"></canvas><div id="vectorResult"></div><p>These invented 3D coordinates illustrate cosine similarity; they are not measured model embeddings.</p>';
case'transformer':return '<h3>Inspect the layer stack</h3><label for="layerSlider">Highlighted block: <span id="layerN">3</span> of 6</label><input id="layerSlider" type="range" min="0" max="5" value="2"><div class="flow-list"><div>1. Normalize & attend <em>MIX TOKENS</em></div><div>2. Add residual <em>KEEP SIGNAL</em></div><div>3. Normalize & feed forward <em>TRANSFORM</em></div><div>4. Add residual <em>NEXT BLOCK</em></div></div><p>Six blocks are drawn for readability. Real depths and widths vary.</p>';
case'attention':return '<h3>Inspect a causal attention matrix</h3><div class="attention" id="attentionMatrix"></div><p id="attentionNote"></p><p>Click a colored cell to inspect its query row. Dark cells are future positions: attention weight zero.</p>';
case'loss':return '<h3>How surprising was the target?</h3><p>Training text: “The sky is <strong>blue</strong>”.</p><label for="prob">Probability assigned to “blue”</label><input id="prob" type="range" min="1" max="99" value="25"><div class="statrow"><div class="stat"><strong id="probN"></strong><small>Target probability</small></div><div class="stat"><strong id="lossN"></strong><small>Loss (nats)</small></div></div><p>Move right: as the correct token becomes more likely, loss falls. This uses the exact negative-log formula.</p>';
case'gradient':return '<h3>Train a one-weight model</h3><p>Input x = 2 · target y = 4 · prediction = 2w</p><canvas id="lossCanvas" width="550" height="260" class="mini-canvas" aria-label="Loss history for gradient descent"></canvas><div class="statrow"><div class="stat"><strong id="weightN"></strong><small>Weight w</small></div><div class="stat"><strong id="trainLoss"></strong><small>Squared error</small></div></div><label for="rate">Learning rate: <span id="rateN">0.08</span></label><input id="rate" type="range" min=".01" max=".2" step=".01" value=".08"><button id="train" class="primary">Run one training step ↻</button><button id="trainReset" class="secondary">Reset experiment</button><p id="gradientNote" aria-live="polite"></p>';
case'gpu':return '<h3>Divide the work across GPUs</h3><label for="parallel">Parallelism strategy</label><select id="parallel"><option value="data">Data — different batches</option><option value="tensor">Tensor — split a matrix</option><option value="pipeline">Pipeline — split the layers</option></select><label for="gpuCount">Active GPUs: <span id="gpuN">4</span></label><input id="gpuCount" type="range" min="1" max="8" value="4"><div class="gpu-grid" id="gpuGrid"></div><p id="gpuNote"></p><p>Conceptual assignment only; this is not a speed or hardware benchmark.</p>';
case'post':return '<h3>Explore the refinement signals</h3><label for="refinement">Training approach</label><select id="refinement"><option value="sft">Supervised fine-tuning</option><option value="preference">Preference learning</option><option value="rl">Reinforcement learning</option></select><div class="callout" id="refinementNote"></div>';
case'inference':return '<h3>Generate a tiny continuation</h3><label for="prompt">Choose a prompt</label><select id="prompt"><option>The sky is</option><option>A cat is</option><option>AI can</option></select><div class="generated" id="generated" aria-live="polite">The sky is</div><label for="temperature">Temperature: <span id="tempN">0.8</span></label><input id="temperature" type="range" min=".1" max="2" step=".1" value=".8"><div class="bars" id="probBars"></div><button id="generate" class="primary">Sample the next token →</button><button id="genReset" class="secondary">Reset continuation</button><p>Local toy probabilities, not a live AI response. Bars show the next-token distribution; each selected token extends the context.</p>';
case'complete':return '<h3>Trace either journey again</h3><div class="flow-list"><div>Examples → token IDs → vectors</div><div>Transformer → next-token scores</div><div>Training: loss → gradients → updates</div><div>Inference: sample → append → repeat</div></div><button class="primary" data-go="1">Explore training again →</button><button class="secondary" data-go="10">Explore inference →</button>';
}return expansion?.labHTML(kind)||'';}
function select(i,move=true){current=(i+lessons.length)%lessons.length;const l=lessons[current];$('#lesson').innerHTML=`<div class="fade"><div class="lesson-head"><span class="eyebrow mint">${String(current+1).padStart(2,'0')} / THE JOURNEY</span><span>${l.tag}</span></div><h2>${l.title}</h2><p class="intro">${l.intro}</p><div class="callout"><strong>${l.key}</strong>${l.take}</div><div class="lab">${labHTML(l.lab)}</div><details class="deep"><summary>${l.deep}</summary><p>${l.body}</p>${l.formula?`<code class="formula">${l.formula}</code>`:''}</details><details class="deep"><summary>${l.extra}</summary><p>${l.more}</p></details><p class="notice">CONCEPTUAL MODEL · Geometry, numbers and examples are illustrative. <button class="source-inline" onclick="document.querySelector('#sources').showModal()">Read the sources ↗</button></p></div>`;
$('#detail').scrollTop=0;$$('.chapter').forEach((e,k)=>{e.classList.toggle('active',k===current);e.setAttribute('aria-current',k===current?'step':'false')});$$('.tour-dots button').forEach((e,k)=>e.classList.toggle('active',k===current));$('#footerTitle').textContent=l.nav;$('#footerSub').textContent=current?'Inspect the parts. Follow the internal flow.':'Start anywhere, or follow the guided journey.';$('#stepCount').textContent=`${String(current+1).padStart(2,'0')} / ${lessons.length}`;$('#next').innerHTML=current===lessons.length-1?'Return to overview <span>↺</span>':current===0?'Begin the journey <span>→</span>':'Next chapter <span>→</span>';$('#previous').disabled=current===0;$('#sceneCaption').textContent=l.take;if(move){targetFocus=current===0||current===lessons.length-1?[0,0,0]:(pos[current]||[0,0,0]).map(x=>x*.32);targetZoom=current===0||current===lessons.length-1?1:1.13}expansion?.enter();bindLab();expansion?.bindLab();}
$('#chapterList').innerHTML=lessons.map((l,i)=>`${i===11?'<div class="nav-group">MODERN MODELS & SYSTEMS</div>':''}<button class="chapter" data-chapter="${i}"><span class="num">${String(i+1).padStart(2,'0')}</span>${l.nav}<span class="arrow">›</span></button>`).join('');$('#dots').innerHTML=lessons.map((l,i)=>`<button data-chapter="${i}" aria-label="${l.nav}"></button>`).join('');$$('[data-chapter]').forEach(b=>b.onclick=()=>select(+b.dataset.chapter));$('#next').onclick=()=>select(current+1);$('#previous').onclick=()=>select(current-1);$('#sourcesOpen').onclick=()=>$('#sources').showModal();$('#sourcesClose').onclick=()=>$('#sources').close();$('#sources').addEventListener('click',e=>{if(e.target===$('#sources')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));if(mode==='inference')select(10);else if(mode==='training')select(1);else select(0)});
function bindLab(){$$('[data-go]').forEach(b=>b.onclick=()=>select(+b.dataset.go));if($('#dataExample')){const f=()=>{const words=$('#dataExample').value.split(' ');$('#dataPairs').innerHTML='<div class="flow-list" style="margin-top:14px">'+words.slice(1).map((w,i)=>`<div>${words.slice(0,i+1).join(' ')} <em>→ ${w}</em></div>`).join('')+'</div>'};$('#dataExample').onchange=f;f()}
if($('#tokenInput')){const f=()=>{let s=$('#tokenInput').value;const vocab=['Gener','ative',' AI',' learns',' patterns','The',' sky',' is',' blue',' cat','a','the'];const tokens=[];while(s){let v=vocab.find(x=>s.startsWith(x));if(v){tokens.push([v,vocab.indexOf(v)+1]);s=s.slice(v.length)}else{const c=[...s][0];tokens.push([c,100+c.codePointAt(0)]);s=s.slice(c.length)}}$('#tokenOutput').innerHTML=tokens.map(([t,id])=>`<span class="token">${esc(t.replace(/ /g,'␠').replace(/\n/g,'↵'))}<small>${id}</small></span>`).join('');$('#tokenCount').textContent=`${tokens.length} tokens · ${[...$('#tokenInput').value].length} characters`;};$('#tokenInput').oninput=f;f()}
if($('#vectorWord')){$('#vectorWord').onchange=drawVectors;drawVectors()}
if($('#layerSlider')){$('#layerSlider').value=layer;$('#layerN').textContent=layer+1;$('#layerSlider').oninput=e=>{layer=+e.target.value;$('#layerN').textContent=layer+1}}
if($('#attentionMatrix'))drawAttention();
if($('#prob')){const f=()=>{$('#probN').textContent=$('#prob').value+'%';$('#lossN').textContent=(-Math.log(+$('#prob').value/100)).toFixed(3)};$('#prob').oninput=f;f()}
if($('#train')){updateGradient();$('#rate').oninput=()=>$('#rateN').textContent=(+$('#rate').value).toFixed(2);$('#train').onclick=()=>{const grad=4*(2*trainW-4),lr=+$('#rate').value;trainW-=lr*grad;trainStep++;history.push((2*trainW-4)**2);if(history.length>35)history.shift();updateGradient();$('#gradientNote').textContent=`Step ${trainStep}: gradient ${grad.toFixed(4)}. Subtracted ${(lr*grad).toFixed(4)} from the weight.`};$('#trainReset').onclick=()=>{trainW=.2;trainStep=0;history=[12.96];updateGradient()}}
if($('#gpuCount')){$('#gpuCount').value=gpuCount;$('#parallel').value=parallel;$('#gpuCount').oninput=()=>{gpuCount=+$('#gpuCount').value;drawGPUs()};$('#parallel').onchange=()=>{parallel=$('#parallel').value;drawGPUs()};drawGPUs()}
if($('#refinement')){const f=()=>$('#refinementNote').textContent=({sft:'A high-quality prompt and response demonstrate the desired behavior. The model learns to increase the probability of the response tokens.',preference:'Two candidate responses are compared. A preference objective shifts the model toward preferred responses; some approaches use a separate reward model.',rl:'A response or action receives a reward, for example from a verifiable solution. Policy updates aim to make high-reward behavior more likely.'})[$('#refinement').value];$('#refinement').onchange=f;f()}
if($('#generate')){genTokens=[];temp=.8;updateGeneration();$('#prompt').onchange=()=>{genTokens=[];updateGeneration()};$('#temperature').oninput=()=>{temp=+$('#temperature').value;updateGeneration()};$('#generate').onclick=()=>{const choices=getChoices(),ps=probabilities(choices);let r=Math.random(),idx=ps.length-1;for(let i=0;i<ps.length;i++){r-=ps[i];if(r<=0){idx=i;break}}genTokens.push(choices[idx][0]);updateGeneration()};$('#genReset').onclick=()=>{genTokens=[];updateGeneration()}}
}
function drawAttention(){const words=['The','cat','sat','down'],weights=[[1,0,0,0],[.3,.7,0,0],[.15,.6,.25,0],[.08,.18,.54,.2]];$('#attentionMatrix').innerHTML='<div></div>'+words.map(w=>`<div>${w}</div>`).join('')+weights.map((r,i)=>`<div>${words[i]}</div>`+r.map((v,j)=>`<button ${j>i?'disabled':''} class="${j>i?'mask':'attn'}" data-row="${i}" style="${j<=i?`background:rgba(104,203,157,${.15+v*.7});border-color:${i===attnRow?'#a8f3cc':'#395447'}`:''}" aria-label="${words[i]} attends to ${words[j]} with weight ${v}">${j>i?'—':v.toFixed(2)}</button>`).join('')).join('');$('#attentionNote').textContent=`Query “${words[attnRow]}” can use ${attnRow+1} position${attnRow?'s':''}. This row sums to 1.00.`;$$('[data-row]').forEach(b=>b.onclick=()=>{attnRow=+b.dataset.row;drawAttention()})}
function drawVectors(){const vectors={cat:[.8,.7,.2],kitten:[.75,.8,.25],dog:[.6,.55,.35],car:[-.5,.15,.9]},v=vectors[$('#vectorWord').value],a=vectors.cat,cos=a.reduce((s,x,i)=>s+x*v[i],0)/(Math.hypot(...a)*Math.hypot(...v));$('#vectorResult').innerHTML=`<code class="formula">cat [${a.join(', ')}]<br>${$('#vectorWord').value} [${v.join(', ')}]</code><div class="stat"><strong>${cos.toFixed(3)}</strong><small>Cosine similarity (−1 to 1)</small></div>`;const c=$('#vectorCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);const origin=[235,235],p=v=>[origin[0]+v[0]*180-v[2]*90,origin[1]-v[1]*170+v[2]*40];ctx.lineWidth=2;[[1,0,0],[0,1,0],[0,0,1]].forEach((v,i)=>{ctx.strokeStyle='#345261';const q=p(v);ctx.beginPath();ctx.moveTo(...origin);ctx.lineTo(...q);ctx.stroke();ctx.fillStyle='#8aa9b8';ctx.font='19px sans-serif';ctx.fillText('xyz'[i],q[0]+8,q[1])});[[a,'cat','#82e5b5'],[v,$('#vectorWord').value,'#b6a3ff']].forEach(([v,label,color])=>{const q=p(v);ctx.strokeStyle=color;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(...origin);ctx.lineTo(...q);ctx.stroke();ctx.fillStyle=color;ctx.beginPath();ctx.arc(...q,6,0,Math.PI*2);ctx.fill();ctx.font='20px sans-serif';ctx.fillText(label,q[0]+10,q[1]+(label==='cat'?19:-12))})}
function updateGradient(){$('#weightN').textContent=trainW.toFixed(4);$('#trainLoss').textContent=((2*trainW-4)**2).toFixed(5);$('#gradientNote').textContent=`Step ${trainStep} · Prediction ${(2*trainW).toFixed(4)} · Target 4`;const c=$('#lossCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,550,260);ctx.strokeStyle='#2d4653';ctx.lineWidth=1;[45,105,165,225].forEach(y=>{ctx.beginPath();ctx.moveTo(35,y);ctx.lineTo(525,y);ctx.stroke()});ctx.fillStyle='#92aebb';ctx.font='17px sans-serif';ctx.fillText('loss',35,25);ctx.fillText('training steps →',340,253);ctx.strokeStyle='#b6a3ff';ctx.lineWidth=4;ctx.beginPath();history.forEach((v,i)=>{let x=40+i/(Math.max(8,history.length-1))*465,y=225-v/13*180;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();history.forEach((v,i)=>{ctx.beginPath();ctx.arc(40+i/Math.max(8,history.length-1)*465,225-v/13*180,4,0,7);ctx.fillStyle='#c4b8ff';ctx.fill()})}
function drawGPUs(){$('#gpuN').textContent=gpuCount;$('#gpuGrid').innerHTML=Array.from({length:8},(_,i)=>`<div class="gpu ${i>=gpuCount?'off':''}">GPU ${i+1}<br>${i>=gpuCount?'idle':parallel==='data'?'batch '+(i+1):parallel==='tensor'?'shard '+(i+1):'stage '+(i+1)}</div>`).join('');$('#gpuNote').textContent=parallel==='data'?`${gpuCount} replica${gpuCount>1?'s':''} process different batches, then synchronize gradients. Each replica has the same model weights.`:parallel==='tensor'?`A matrix operation is divided into ${gpuCount} shard${gpuCount>1?'s':''}. Devices exchange partial results to complete the operation.`:`Layers are assigned to ${gpuCount} stage${gpuCount>1?'s':''}. Microbatches flow through the stages; idle pipeline gaps can limit utilization.`}
function getChoices(){const p=$('#prompt').value,n=genTokens.length;if(n>=4)return [['<end>',1]];if(n===0)return p==='The sky is'?[['blue',2.1],['clear',1.3],['cloudy',.7]]:p==='A cat is'?[['sleeping',2],['playing',1.4],['curious',.6]]:[['generate',2],['assist',1.4],['learn',.8]];if(p==='AI can'){if(n===1)return genTokens[0]==='generate'?[['text',2],['images',1.2],['code',1]]:genTokens[0]==='assist'?[['people',2],['teams',1.2],['learners',1]]:[['patterns',2],['representations',1.2],['relationships',1]];if(n===2)return [['from',1.6],['with',.9]];return [['examples.',2],['context.',1.2]]}if(n===1)return [['and',1.5],['today.',1],['now.',.7]];if(genTokens.at(-1).endsWith('.'))return [['<end>',1]];if(n===2)return p==='The sky is'?[['beautiful',2],['bright',1.4],['vast',.9]]:[['quiet',2],['content',1.4],['alert',.9]];return [['today.',1.8],['now.',1.2]]}
function probabilities(choices){const mx=Math.max(...choices.map(c=>c[1])),e=choices.map(c=>Math.exp((c[1]-mx)/temp)),sum=e.reduce((a,b)=>a+b,0);return e.map(x=>x/sum)}
function updateGeneration(){const ended=genTokens.includes('<end>');$('#generated').textContent=$('#prompt').value+(genTokens.length?' '+genTokens.filter(t=>t!=='<end>').join(' '):'');$('#tempN').textContent=temp.toFixed(1);const c=getChoices(),p=probabilities(c);$('#probBars').innerHTML=ended?'<p>End token selected. The continuation is complete.</p>':c.map(([w],i)=>`<div class="barline"><span>${esc(w)}</span><div class="bartrack"><div class="barfill" style="width:${100*p[i]}%"></div></div><span>${(100*p[i]).toFixed(0)}%</span></div>`).join('');$('#generate').disabled=ended;$('#generate').textContent=ended?'Generation complete':'Sample the next token →'}
// A perspective 3D diagram renderer. Every mesh, connection and camera lives in world coordinates.
const canvas=$('#world'),ctx=canvas.getContext('2d');let W=800,H=700,DPR=1,hitNodes=[],drag=null;
const nodes=[{i:1,p:pos[1],label:'02  Training data'},{i:2,p:pos[2],label:'03  Tokenization'},{i:3,p:pos[3],label:'04  Vector space'},{i:4,p:pos[4],label:'05  Transformer'},{i:6,p:pos[6],label:'07  Prediction & loss'},{i:7,p:pos[7],label:'08  Backpropagation'},{i:8,p:pos[8],label:'09  GPU compute'},{i:9,p:pos[9],label:'10  Post-training'},{i:10,p:pos[10],label:'11  Inference'}];
$('#sceneLabels').innerHTML=nodes.map(n=>`<span class="node-label" id="label${n.i}">${n.label}</span>`).join('');
function resize(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;DPR=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0)}new ResizeObserver(resize).observe(canvas);
function project(p){let x=p[0]-focus[0],y=p[1]-focus[1],z=p[2]-focus[2],xx=x*Math.cos(angle)-z*Math.sin(angle),zz=x*Math.sin(angle)+z*Math.cos(angle),yy=y*Math.cos(tilt)-zz*Math.sin(tilt),depth=y*Math.sin(tilt)+zz*Math.cos(tilt);const detailed=!!microScenes[current];const scale=(detailed?Math.min(W/13.5,(H-360)/8):Math.min(W/21.5,(H-220)/13))*zoom*28/(28+depth);return [W*.48+xx*scale,H*(detailed?.43:.53)-yy*scale,depth,scale]}
function rgba(hex,a){return `rgba(${parseInt(hex.slice(1,3),16)},${parseInt(hex.slice(3,5),16)},${parseInt(hex.slice(5,7),16)},${a})`}
function line3(a,b,color,width=1,alpha=1){const p=project(a),q=project(b);ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(q[0],q[1]);ctx.strokeStyle=rgba(color,alpha);ctx.lineWidth=width;ctx.stroke()}
let faces=[];function cube(p,size,color,opacity=.4,id=0){const [x,y,z]=p,[w,h,d]=size;const v=[[-w,-h,-d],[w,-h,-d],[w,h,-d],[-w,h,-d],[-w,-h,d],[w,-h,d],[w,h,d],[-w,h,d]].map(a=>project([x+a[0]/2,y+a[1]/2,z+a[2]/2]));[[0,1,2,3],[4,5,6,7],[0,4,7,3],[1,5,6,2],[3,2,6,7],[0,1,5,4]].forEach((f,i)=>{faces.push({v:f.map(k=>v[k]),z:f.reduce((s,k)=>s+v[k][2],0)/4,color,opacity:opacity*(i===4?1:.56),edge:opacity*.8,id})})}
function dot3(p,color,r=3,alpha=1,glow=false){const q=project(p);ctx.fillStyle=rgba(color,alpha);if(glow){ctx.shadowBlur=12;ctx.shadowColor=color}ctx.beginPath();ctx.arc(q[0],q[1],r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
function active(i){if(mode==='training'&&i===10)return .2;if(mode==='inference'&&[1,6,7,9].includes(i))return .15;return current===0||current===lessons.length-1||i===current||(current===5&&i===4)?1:.63}
const edges=[[1,2],[2,3],[3,4],[4,6],[6,7],[7,4],[4,9],[9,10]];
function path(a,b,t,lift=0){return [a[0]+(b[0]-a[0])*t,a[1]+(b[1]-a[1])*t+Math.sin(t*Math.PI)*lift,a[2]+(b[2]-a[2])*t]}
function scene(dt=0){if(expansion?.hasScene())return expansion.render(dt);ctx.clearRect(0,0,W,H);for(let n=-12;n<=12;n++){line3([n,-3.2,-9],[n,-3.2,8],'#34515e',.65,.23);line3([-12,-3.2,n],[12,-3.2,n],'#34515e',.65,.23)}
// Directional routes: the violet return arc is the training gradient loop.
edges.forEach(([a,b],k)=>{const reverse=a===7,ca=reverse?'#c0a5ff':a>=9?'#f3bd71':col[a],alp=Math.min(active(a),active(b));let last=pos[a];for(let j=1;j<=30;j++){const p=path(pos[a],pos[b],j/30,reverse?3:.4);line3(last,p,ca,reverse?1.5:1,alp*.38);last=p}for(let j=0;j<3;j++){const t=(tick*.11+j/3+k*.12)%1;dot3(path(pos[a],pos[b],t,reverse?3:.4),ca,2,alp,true)}const arrow=project(path(pos[a],pos[b],.65,reverse?3:.4)),prev=project(path(pos[a],pos[b],.6,reverse?3:.4)),ang=Math.atan2(arrow[1]-prev[1],arrow[0]-prev[0]);ctx.strokeStyle=rgba(ca,alp*.8);ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(arrow[0]-6*Math.cos(ang-.5),arrow[1]-6*Math.sin(ang-.5));ctx.lineTo(arrow[0],arrow[1]);ctx.lineTo(arrow[0]-6*Math.cos(ang+.5),arrow[1]-6*Math.sin(ang+.5));ctx.stroke()});
if(mode==='inference'){const a=[7,0,3],b=[-5,0,1];for(let j=0;j<40;j++)line3(path(a,b,j/40,-2.4),path(a,b,(j+1)/40,-2.4),'#f3bd71',1,.45);for(let j=0;j<5;j++)dot3(path(a,b,(tick*.08+j/5)%1,-2.4),'#f3bd71',2,.9,true)}
faces=[];
// Data records, tokenizer lanes and a three-dimensional embedding cloud.
for(let i=0;i<6;i++)cube([-8+(i%2)*.7,.2+Math.floor(i/2)*.32,1],[1.2,.1,1.4],'#82e5b5',.4*active(1),1);
for(let i=0;i<5;i++)cube([-5+(i%3)*.47-.4,.15+Math.floor(i/3)*.42,1],[.36,.32,.6],'#82e5b5',.55*active(2),2);
cube([-3,1,-3],[2.1,2.1,2.1],'#82e5b5',.04*active(3),3);
// Six transparent transformer blocks, with internal neuron lanes.
for(let l=0;l<6;l++){let y=-.6+l*.48;let color=(current===4&&l===layer)?'#d5c8ff':'#b6a3ff';cube([0,y,0],[2.65,.12,2.2],color,(current===4&&l===layer?.7:.27)*active(4),4);for(let j=0;j<6;j++)cube([-.9+(j%3)*.85,y+.18,-.55+Math.floor(j/3)*1.1],[.25,.16,.25],color,.65*active(4),4)}
// Predicted vocabulary scores.
for(let j=0;j<5;j++)cube([3.1+j*.28,.1+(j===2?1.1:.3+j*.13)/2,-3],[.2,j===2?1.1:.3+j*.13,.7],'#b6a3ff',.6*active(6),6);
// Gradient routing lattice.
for(let j=0;j<4;j++)cube([-.6+j*.4,.1,-5],[.23,.35+j*.15,.5],'#b6a3ff',.55*active(7),7);
// Accelerator plane supports the entire model, not a step after it.
cube([0,-2.7,2.3],[6.4,.2,2.4],'#76b9ef',.2*active(8),8);for(let j=0;j<8;j++){const on=current===8?j<gpuCount:true;cube([-2.3+(j%4)*1.5,-2.46,1.7+Math.floor(j/4)*1.15],[.9,.2,.75],on?'#82bfff':'#435461',on?.56:.15,8);for(let k=0;k<4;k++)cube([-2.54+(j%4)*1.5+(k%2)*.38,-2.31,1.5+Math.floor(j/4)*1.15+Math.floor(k/2)*.3],[.18,.05,.15],on?'#c6e6ff':'#435461',on?.7:.1,8)}
for(let j=0;j<3;j++)cube([4,j*.38,.5],[1.4,.2,1.2],'#b6a3ff',.4*active(9),9);
for(let j=0;j<4;j++)cube([6.3+j*.48,.1+(j%2)*.28,3],[.36,.38,.9],'#f3bd71',.55*active(10),10);
faces.sort((a,b)=>b.z-a.z);for(const f of faces){ctx.beginPath();f.v.forEach((v,k)=>k?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();ctx.fillStyle=rgba(f.color,f.opacity);ctx.fill();ctx.strokeStyle=rgba(f.color,f.edge);ctx.lineWidth=.7;ctx.stroke()}
// Vectors and points in the embedding space.
[[1.3,0,0],[0,1.3,0],[0,0,1.3]].forEach(v=>line3([-3,.25,-3],[-3+v[0],.25+v[1],-3+v[2]],'#b4f2d0',1,active(3)*.6));for(let j=0;j<28;j++){const p=[-3+Math.sin(j*2.4)*.85,1+Math.cos(j*1.9)*.8,-3+Math.sin(j*3.3)*.8];dot3(p,j%3?'#82e5b5':'#b6a3ff',j%6?1.7:3,active(3));if(j%5===0)line3([-3,.25,-3],p,'#82e5b5',.7,active(3)*.3)}
for(let j=0;j<9;j++){const x=-.9+(j%3)*.85,z=-.55+Math.floor(j/3)*.55;line3([x,-.5,z],[x,2.1,z],'#cbbaff',.6,active(4)*.28);dot3([x,-.5+(tick*.5+j*.3)%2.6,z],'#d9cdff',2,active(4),true)}
// Dashed compute links emphasize hardware executing the model.
for(let j=0;j<3;j++)for(let s=0;s<8;s+=2)line3([-1+j,-2.3+s*.17,1],[-1+j,-2.3+(s+1)*.17,1],'#82bfff',.8,.3);
hitNodes=[];const placed=[];for(const n of [...nodes].sort((a,b)=>(b.i===current)-(a.i===current))){const q=project(n.p),label=$('#label'+n.i);hitNodes.push({x:q[0],y:q[1],i:n.i,r:Math.max(24,q[3]*1.4)});let x=q[0],y=q[1]+(n.i===8?30:n.i===4?58:32);const wid=label.offsetWidth||120;let hide=(mode==='inference'&&[1,6,7,9].includes(n.i))||(mode==='training'&&n.i===10);for(let loop=0;loop<5;loop++){if(placed.some(p=>Math.abs(p.x-x)<(p.w+wid)/2+4&&Math.abs(p.y-y)<25))y+=26;else break}x=Math.max(wid/2+8,Math.min(W-wid/2-8,x));if(y>H-165||y<200)hide=true;label.style.left=x+'px';label.style.top=y+'px';label.style.opacity=hide?'0':String(active(n.i));label.classList.toggle('selected',n.i===current||(current===5&&n.i===4));if(!hide)placed.push({x,y,w:wid})}
}
let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(playing)tick+=dt;zoom+=(targetZoom-zoom)*.08;focus=focus.map((v,i)=>v+(targetFocus[i]-v)*.07);scene(dt);requestAnimationFrame(frame)}
canvas.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(drag){const dx=e.clientX-drag.lastX,dy=e.clientY-drag.lastY;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5)drag.moved=true;angle+=dx*.007;tilt=Math.min(1.25,Math.max(.12,tilt+dy*.005));drag.lastX=e.clientX;drag.lastY=e.clientY;canvas.style.cursor='grabbing'}else{const r=canvas.getBoundingClientRect();canvas.style.cursor=hitNodes.some(n=>Math.hypot(n.x-(e.clientX-r.left),n.y-(e.clientY-r.top))<n.r)?'pointer':'grab'}});canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved){const r=canvas.getBoundingClientRect(),hits=hitNodes.filter(n=>Math.hypot(n.x-(e.clientX-r.left),n.y-(e.clientY-r.top))<n.r).sort((a,b)=>Math.hypot(a.x-(e.clientX-r.left),a.y-(e.clientY-r.top))-Math.hypot(b.x-(e.clientX-r.left),b.y-(e.clientY-r.top)));if(hits[0]){if(hits[0].part)expansion.setPart(hits[0].i);else select(hits[0].i)}}drag=null;canvas.style.cursor='grab'});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();targetZoom=Math.min(2.2,Math.max(.6,targetZoom-e.deltaY*.001))},{passive:false});canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Home'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')angle-=.12;if(e.key==='ArrowRight')angle+=.12;if(e.key==='ArrowUp')tilt=Math.min(1.25,tilt+.08);if(e.key==='ArrowDown')tilt=Math.max(.12,tilt-.08);if(e.key==='+')targetZoom=Math.min(2.2,targetZoom+.15);if(e.key==='-')targetZoom=Math.max(.6,targetZoom-.15);if(e.key==='Home')resetView()});
function resetView(){angle=microScenes[current]?-.12:-.38;tilt=microScenes[current]?.42:.61;targetZoom=microScenes[current]?1.2:1;targetFocus=[0,0,0]}$('#resetView').onclick=resetView;$('#zoomIn').onclick=()=>targetZoom=Math.min(2.2,targetZoom+.15);$('#zoomOut').onclick=()=>targetZoom=Math.max(.6,targetZoom-.15);function updateMotion(){$('#motion').textContent=playing?'Ⅱ':'▷';$('#motion').setAttribute('aria-label',playing?'Pause animation':'Play animation')}$('#motion').onclick=()=>{playing=!playing;updateMotion()};updateMotion();
expansion=createExpansion({
state:()=>({current,lesson:lessons[current],anchor:pos[current]||[0,0,0],reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,canvas,ctx,W,H,tick,playing,layer,attnRow,trainW,gpuCount,parallel}),
project,cube,line3,dot3,path,rgba,resume:()=>{playing=true;updateMotion()},
camera:detailed=>{targetFocus=[0,0,0];focus=[0,0,0];angle=detailed?-.12:-.38;tilt=detailed?.42:.61;zoom=matchMedia('(prefers-reduced-motion: reduce)').matches?(detailed?1.2:1):.7;targetZoom=detailed?1.2:1},
clearFaces:()=>faces=[],flushFaces:()=>{faces.sort((a,b)=>b.z-a.z);for(const f of faces){ctx.beginPath();f.v.forEach((v,k)=>k?ctx.lineTo(v[0],v[1]):ctx.moveTo(v[0],v[1]));ctx.closePath();ctx.fillStyle=rgba(f.color,f.opacity);ctx.fill();ctx.strokeStyle=rgba(f.color,f.edge);ctx.lineWidth=.8;ctx.stroke()}},setHits:h=>hitNodes=h
});select(0,false);resize();requestAnimationFrame(frame);
