// Additional chapters use the same lesson contract as the original atlas.
export const newLessons = [
{nav:'Reinforcement learning',title:'Try an outcome.<br>Learn from its reward.',tag:'TRAINING',intro:'A policy is a model that chooses outputs or actions. Reinforcement learning updates that policy using reward signals from sampled outcomes. In language models, a rollout can be a complete generated response.',key:'Reward shapes the policy',take:'Sampling creates rollouts. Scoring assigns rewards. A policy objective, gradients and an optimizer change weights. This is distinct from an agent merely retrying a task.',lab:'rl',deep:'RLHF, verifiable rewards, and DPO',body:'RLHF can learn a reward model from human comparisons, then use it for policy optimization. Verifiable rewards can score checkable outcomes such as test results. Algorithms differ in their use of baselines, clipping and reference-policy penalties. DPO optimizes directly from preference pairs; it is not an online rollout-and-reward RL algorithm.',extra:'The reward is not the goal itself',more:'A convenient score may be an imperfect proxy for useful behavior. Reward hacking, biased feedback and weak checks can teach unwanted shortcuts. Evaluate on independent tasks and inspect failures. The experiment here is exact expected-reward optimization for a two-action toy policy, not PPO, GRPO or a frontier training run.',source:'rl'},
{nav:'Prompt engineering',title:'Make the task<br>and expected output clear.',tag:'APPLICATION',intro:'Prompt engineering organizes instructions, examples and output requirements supplied to a model. These tokens influence generation through the same inference process you already explored.',key:'Instructions become input tokens',take:'A prompt does not install a new skill into the weights. Measure whether an instruction or example actually helps on representative tasks.',lab:'prompting',deep:'What can a good prompt contain?',body:'State the task, relevant context, constraints and the desired output format. A few examples can demonstrate a pattern. Keep quoted source material separate from instructions. A structured-output schema can constrain format when the serving system supports it, but valid JSON is not necessarily a correct answer.',extra:'Reasoning prompts are not a guarantee',more:'Breaking a task into checkable steps can help some tasks. Asking a model to think harder does not establish that its conclusion is true, and generated explanations may not faithfully reveal internal computation. Compare approaches against task-specific checks. This chapter assembles prompt text locally; it does not call an AI service.',source:'prompt'},
{nav:'Context engineering',title:'Choose what the model<br>can see on this turn.',tag:'APPLICATION',intro:'Context engineering selects and maintains the information sent into a model call: instructions, recent messages, relevant documents, tool definitions and tool results.',key:'A finite working context',take:'Context is input to inference. Longer context is not automatically better. Summaries can lose details, and useful evidence must remain available.',lab:'context',deep:'Memory versus model weights',body:'Applications can store facts, notes or prior messages outside the model and retrieve them later. That storage is not a weight update. The next request only benefits from information that is actually included or accessed through tools.',extra:'What changes across turns?',more:'An application can retrieve relevant material, drop stale tool output and summarize earlier work. Each choice trades space against information loss. The toy budget uses illustrative token counts, not a tokenizer or a product context-window specification.',source:'context'},
{nav:'Retrieval & RAG',title:'Bring evidence<br>into the model’s context.',tag:'APPLICATION',intro:'Retrieval-augmented generation retrieves relevant external material and supplies it to a model before it answers. Indexing and retrieval are separate from the model’s learned weights.',key:'Retrieve, then generate',take:'Search finds candidate evidence. The application packages that evidence into context. The model generates an answer that still needs support checking.',lab:'rag',deep:'What happens before a query?',body:'Documents are split into retrievable chunks and indexed. A retriever may use dense embeddings, keyword search or a hybrid. At query time it selects candidates; reranking may improve the final selection. The local demonstration uses lexical overlap, not neural embeddings.',extra:'Why retrieval can still fail',more:'A retriever can miss the right passage or return outdated or irrelevant text. A model can misread good evidence or invent citations. Preserve document identifiers and evaluate retrieval and answer support separately. A vector index is one implementation choice, not a requirement for all RAG.',source:'rag'},
{nav:'Agent loops & tools',title:'Act, observe,<br>and decide what comes next.',tag:'ORCHESTRATION',intro:'An agent loop repeatedly gives a model context, executes permitted tool requests and returns the results for the next decision. The model may continue, revise its approach or finish.',key:'“Loop engineering” is an informal label here',take:'This chapter uses agent-loop design: state, actions, observations, checks and stopping conditions. Running this loop ordinarily leaves the model’s weights unchanged.',lab:'agent',deep:'What really executes a tool?',body:'The model proposes a structured tool call. Application code validates it and executes the tool. The result becomes a new observation. A model saying it used a tool is not evidence that execution happened; the application needs an actual result.',extra:'Keep the loop accountable',more:'Define the goal, tool permissions, error handling and a step budget. Check external results before continuing, and stop when success is verified or the budget is exhausted. The scene shows a deterministic local calculator trace, not hidden model reasoning or a live autonomous agent.',source:'agents'},
{nav:'Graphs & GraphRAG',title:'Two kinds of graph.<br>Two different jobs.',tag:'ORCHESTRATION',intro:'A workflow graph connects operations and decisions. A knowledge graph connects entities and relationships. GraphRAG uses graph-structured knowledge to help retrieve and organize evidence for generation.',key:'“Graph engineering” needs a specific meaning',take:'Workflow edges mean “what runs next.” Knowledge-graph edges mean relationships in data. Neither is the model’s neural network.',lab:'graphs',deep:'Graph-based workflows',body:'A workflow can branch on a condition, run independent operations and merge their results. State records intermediate outputs. An edge can return to an earlier step, creating a loop. The chapter’s workflow branches between retrieval and a calculator.',extra:'Knowledge graphs and GraphRAG',more:'A graph may connect people, projects and documents. GraphRAG systems can extract entities and relationships, organize communities and use summaries during retrieval. Extraction and summaries can be wrong; retain provenance and evaluate answer support. GraphRAG is not automatically preferable to simpler retrieval.',source:'graphs'},
{nav:'Mixture of experts',title:'Route each token<br>to selected expert networks.',tag:'MODEL',intro:'A sparse mixture-of-experts layer uses a learned router to select a subset of feed-forward expert networks for each token. Their weighted outputs return to the model’s hidden representation.',key:'Experts are numerical networks',take:'The experts are not necessarily human-named specialists. Sparse activation reduces active computation relative to using every expert, while total stored weights may remain large.',lab:'moe',deep:'What is being routed?',body:'The router scores the token’s hidden vector. A top-k choice activates selected experts, whose outputs are combined using routing weights. Attention and other parts of the architecture may remain shared. Some designs also include shared experts.',extra:'The scaling trade-off',more:'Devices may exchange routed token vectors. Uneven routing can cause load imbalance; balancing mechanisms and capacity handling depend on the model. The four-expert scene uses invented routing scores, not measured activations from a real model.',source:'moe'},
{nav:'Multimodal models',title:'Different signals.<br>Compatible representations.',tag:'MODEL FAMILY',intro:'Multimodal systems process combinations of text, images, audio or video. Modality-specific processing converts inputs into representations the model can combine.',key:'Not every input is text',take:'Image patches or audio features can become model inputs through learned encoders or tokenization schemes. Exact interfaces vary by architecture.',lab:'multimodal',deep:'Follow an image and a question',body:'In one common pattern, an image encoder creates visual features and a projector maps them into a representation compatible with a language model. Text is tokenized and embedded. The model conditions its answer on both. Other architectures use different fusion mechanisms.',extra:'Alignment and limitations',more:'Training examples that link modalities can teach useful relationships between visual, auditory and language features. This does not guarantee reliable counting, spatial reasoning or transcription. The scene is a generic image-plus-text architecture, not a reconstruction of a proprietary model.',source:'multimodal'},
{nav:'Diffusion models',title:'Learn to remove noise.<br>Generate by repeated refinement.',tag:'MODEL FAMILY',intro:'Diffusion is another major generative approach. In a common formulation, training corrupts examples with noise and teaches a network to predict a denoising-related target at different noise levels.',key:'A different generation process',take:'Sampling starts from noise and repeatedly applies learned updates. Many image systems work in a compressed latent space; exact objectives and samplers vary.',lab:'diffusion',deep:'Training versus generation',body:'A training step samples an example, a noise level and noise, then computes a prediction loss. At generation time, a sampler runs a sequence of updates, optionally conditioned on text or other inputs. Latent systems use a decoder to turn the final latent into an image.',extra:'What the experiment does',more:'The voxel display interpolates between a fixed noisy grid and a simple target pattern. It illustrates a denoising trajectory, but it does not run a trained denoiser. Flow-matching systems are related iterative generative approaches with different training formulations; do not assume every image generator follows this exact diffusion recipe.',source:'diffusion'},
{nav:'Evaluation & reliability',title:'Check the result.<br>Then inspect the failure.',tag:'QUALITY',intro:'Evaluation measures how a model or application performs on representative tasks. Check correctness, evidence support, tool outcomes, robustness and the cost of getting a result.',key:'A good-looking answer is not enough',take:'Use independent test cases and explicit criteria. Passing a finite set of checks supports a limited conclusion, not universal reliability.',lab:'eval',deep:'Several different things can go wrong',body:'Retrieval might miss evidence, generation might add an unsupported claim, or a tool may return an error. Measure these components separately as well as end-to-end. A model-based judge is itself fallible; use programmatic checks or human review where appropriate.',extra:'Reasoning and test-time compute',more:'Systems may spend extra inference effort on additional candidates, tool calls or verification. This consumes time and compute without necessarily updating weights. More attempts can help when there is a reliable selection signal; they can also repeat an error. The local experiment checks numeric answers exactly, not arbitrary factual claims.',source:'eval'}
];

const N=(label,type,p,detail,payload)=>({label,type,p,detail,payload});
const S=(name,nodes,edges,steps,note)=>({name,nodes,edges,steps,note});
const chain=n=>Array.from({length:n-1},(_,i)=>[i,i+1]);
// Each lesson has a different internal topology, with named operations and payloads.
export const microScenes={
1:S('Inside the data pipeline',[
N('Source examples','records',[-4,1,0],'Collect eligible text and code with source metadata. This is the raw material, before model computation.','documents + provenance'),
N('Filter & deduplicate','filter',[-1.5,1,-1],'Apply quality filters and remove duplicate material. This does not guarantee that every retained statement is true.','retained documents'),
N('Held-out split','split',[1.5,1,-1],'Reserve evaluation data independently; avoid overlap with training material.','train / validation / test'),
N('Tokenize & pack','tokens',[4,1,0],'Convert training text into IDs and pack bounded sequences with appropriate masks.','token-ID sequences'),
N('Next-token targets','pairs',[1.5,-1.5,2],'Shift the sequence by one token. A position predicts the following token without seeing it.','input IDs → target IDs'),
N('Training batch','matrix',[-1.5,-1.5,2],'Assemble examples and masks into tensors for a forward pass. Batching supplies compute, not new model weights.','batch × sequence tensors')],[[0,1],[1,2],[2,3],[3,4],[4,5]],[0,1,2,3,4,5],'The held-out branch is evaluated separately; it does not supply weight-update gradients.'),
2:S('Inside the tokenizer',[
N('Your text','records',[-4,1,0],'Read characters exactly, including punctuation and spaces. The input box updates this diagram.','raw text'),
N('Match vocabulary pieces','filter',[-1.5,1,-1],'Find reusable pieces from the fixed teaching vocabulary. Unknown characters fall back to character IDs.','piece boundaries'),
N('Token pieces','tokens',[1.5,1,-1],'Text is now a sequence of pieces. These teaching boundaries differ from production tokenizers.','Gener · ative · ␠AI'),
N('Vocabulary lookup','matrix',[4,1,0],'Look up each piece’s integer address. The ID itself is not a semantic quantity.','piece → integer ID'),
N('Ordered ID sequence','pairs',[0,-1.5,2],'Pass the ordered IDs to embedding lookup; retain boundaries and mask information as needed.','IDs → embedding table')],chain(5),[0,1,2,3,4],'Tokenization is discrete preprocessing; the next chapter turns IDs into learned vectors.'),
3:S('Inside embedding lookup',[
N('Token ID','tokens',[-4,0,0],'An ID selects a row in a learned embedding table.','ID = vocabulary address'),
N('Embedding table','matrix',[-1.5,.5,-1],'Rows correspond to vocabulary entries; columns are learned coordinates. Training adjusts these entries.','E[token ID]'),
N('Retrieved vector','vector',[1.5,.5,-1],'The retrieved row is an ordered list of numbers. The comparison control changes the second toy vector.','[0.8, 0.7, 0.2]'),
N('Position information','rings',[4,0,0],'Represent sequence order. Some models add position vectors; others rotate queries and keys inside attention.','vector + order information'),
N('Hidden sequence','network',[0,-1.5,2],'Pass token representations into Transformer layers. Contextual hidden vectors evolve layer by layer.','sequence × hidden dimension')],chain(5),[0,1,2,3,4],'The 3D coordinates are illustrative. Real hidden spaces can have thousands of dimensions.'),
4:S('One expanded Transformer block',[
N('Input + normalization','matrix',[-4,1,-1],'Keep the incoming x for the bypass, while passing normalized x into attention. This is a pre-normalized example.','x for bypass; norm(x) for attention'),
N('Causal multi-head attention','attention',[-1.5,1,-1],'Several heads mix information from allowed token positions using different learned projections.','context-mixed vectors'),
N('Residual addition','merge',[1.5,1,-1],'Add the attention output to the incoming representation. The bypass is a real computational path.','x + attention(norm(x))'),
N('Normalize again','matrix',[4,1,0],'Normalize the updated vectors before the feed-forward computation.','normalized vectors'),
N('Feed-forward network','network',[1.5,-1.5,2],'Apply learned transformations separately at each token position.','nonlinear feature transform'),
N('Residual → next block','merge',[-1.5,-1.5,2],'Add the feed-forward output to its input. The resulting hidden vectors enter the next block.','updated hidden vectors')],[[0,1],[1,2],[0,2],[2,3],[3,4],[4,5],[2,5]],[0,1,2,3,4,5],'Use the block slider in the lesson to select which repeated block this expanded view represents.'),
5:S('Inside causal self-attention',[
N('Q: queries','vector',[-4,1,-1],'Project input hidden vectors into queries. Queries and keys independently enter the score operation.','Q = XWq'),
N('K: keys','vector',[-4,-1.5,2],'Project the same input hidden vectors into keys. Keys are not computed from queries.','K = XWk'),
N('Scaled dot products','matrix',[-.5,1,-1],'Multiply queries by transposed keys and scale by the square root of key dimension.','scores = QKᵀ / √dₖ'),
N('Mask + softmax','attention',[2,1,-1],'Mask future-position scores before normalizing. Allowed row weights sum to one.','causal attention weights'),
N('V: values','vector',[-.5,-1.5,2],'Another projection of the input supplies information to mix. Values bypass the score computation.','V = XWv'),
N('Mix values & combine heads','merge',[4,-1,2],'Multiply attention weights by values. Combine the heads and apply an output projection before residual addition.','weights × V → contextual vectors')],[[0,2],[1,2],[2,3],[3,5],[4,5]],[0,1,2,3,4,5],'Q, K and V are independent learned projections of the same input. Arrows show the actual computational dependencies.'),
6:S('Inside the loss calculation',[
N('Final hidden vector','vector',[-4,1,0],'The last Transformer layer provides a representation at each valid position.','hidden vector h'),
N('Vocabulary projection','matrix',[-1.5,1,-1],'A learned projection produces a score for every vocabulary entry.','logits = hW + b'),
N('Softmax distribution','bars',[1.5,1,-1],'Normalize scores to probabilities. The target-probability slider updates the highlighted bar.','P(next token)'),
N('Correct target','tokens',[4,-1,2],'Read the next token from the prepared training sequence. It was masked from the predicting position.','target: blue'),
N('Negative log probability','loss',[0,-1.5,2],'Select the correct target’s probability and calculate −ln(p); average valid losses for a batch.','scalar loss → backward pass')],[[0,1],[1,2],[2,4],[3,4]],[0,1,2,3,4],'A target with greater predicted probability yields lower loss. Loss values here use exact arithmetic.'),
7:S('Inside one gradient update',[
N('Forward: 2 × w','network',[-4,1,0],'Compute the prediction using the current toy weight. Running a step in the lesson changes this value.','prediction = 2w'),
N('Squared error','loss',[-1,1,-1],'Compare the prediction against target 4. The loss is a scalar, not a training document.','L = (2w − 4)²'),
N('Chain rule','vector',[2,1,-1],'Differentiate the loss through the multiplication operation.','dL/dw = 4(2w − 4)'),
N('Optimizer step','matrix',[4,-1,1],'Subtract learning rate times gradient from the parameter. A real optimizer may maintain additional state.','w ← w − η ∂L/∂w'),
N('Updated weight','tokens',[-1,-1.5,2],'The next forward pass uses this revised weight. Repeat across batches during training.','new numerical parameter')],[[0,1],[1,2],[2,3],[3,4],[4,0]],[0,1,2,3,4],'This feedback loop changes a weight. The agent-loop chapter later changes context and actions instead.'),
8:S('Inside a GPU training job',[
N('Batch dispatcher','split',[-4,1,0],'CPU-side orchestration prepares and schedules data. Work must reach accelerators fast enough.','scheduled tensors'),
N('GPU group A','gpu',[-1,1,-2],'Execute the first group’s assigned work. The strategy selector changes the assignment.','batches / tensor shards / layers'),
N('GPU group B','gpu',[-1,-1.5,2],'Execute another group’s work. Some communication can overlap compute, depending on the implementation.','matrix operations'),
N('Interconnect','rings',[2,0,0],'Move activations, partial results or gradients between devices as the chosen strategy requires.','device-to-device tensors'),
N('Synchronized state','matrix',[4,0,1],'Complete the distributed operation or update. Communication and memory limit practical scaling.','consistent model state')],[[0,1],[0,2],[1,3],[2,3],[3,4]],[0,1,2,3,4],'Data, tensor and pipeline parallelism divide different things; use the selector to see their assignments.'),
9:S('Inside post-training',[
N('Pretrained checkpoint','network',[-4,0,0],'Begin from weights that already learned broad prediction patterns.','pretrained parameters'),
N('Demonstrations','records',[-1,1.5,-2],'Supervised examples pair instructions with desired responses.','prompt–response pairs'),
N('Preference comparisons','pairs',[-1,-1.5,2],'Preference data compares candidate responses. It can support direct preference objectives or reward modeling.','chosen / rejected pairs'),
N('Training objective','loss',[2,0,0],'Choose a method and its corresponding loss. These branches are alternatives, not a mandatory universal sequence.','objective → gradients'),
N('Refined checkpoint','network',[4,0,1],'Update weights and evaluate the result. Reinforcement learning has its own expanded chapter.','updated parameters')],[[0,3],[1,3],[2,3],[3,4]],[0,1,2,3,4],'Supervised fine-tuning, direct preference optimization and reinforcement learning have different objectives.'),
10:S('Inside the inference engine',[
N('Prompt prefill','tokens',[-4,1,0],'Read and embed the known prompt. Its positions can be processed in parallel.','prompt token IDs'),
N('Trained Transformer','network',[-1.5,1,-1],'Compute contextual representations with fixed learned weights.','hidden activations'),
N('KV cache','matrix',[-1.5,-1.5,2],'Store earlier attention keys and values and reuse them during decoding.','cached keys + values'),
N('Next-token distribution','bars',[1.5,1,-1],'Project the final position to logits and apply the chosen decoding rule. The temperature control changes the toy distribution.','next-token probabilities'),
N('Select & append','tokens',[4,0,1],'Sample one token, append it to the sequence and update the cache. An end token can stop the loop.','new token → next decode step')],[[0,1],[1,2],[2,1],[1,3],[3,4],[4,1]],[0,1,2,3,4],'The golden return path is sequential generation. No backward pass or optimizer is needed for ordinary inference.'),
11:S('Inside reinforcement learning',[
N('Policy model','network',[-4,1,0],'The policy assigns probabilities to candidate responses or actions.','πθ(output | prompt)'),
N('Sample rollouts','split',[-1.5,1,-1],'Generate outcomes under the current policy. Each response is a sampled trajectory.','sampled responses'),
N('Reward signal','bars',[1.5,1,-1],'Score outcomes using a reward model, human feedback or a checkable task result.','reward per outcome'),
N('Policy objective','loss',[4,0,1],'Build a learning objective. Baselines and regularizers depend on the algorithm.','policy loss / expected reward'),
N('Gradients & optimizer','matrix',[0,-1.5,2],'Differentiate the objective and update policy parameters; gather new rollouts as the training method requires.','updated θ → policy')],[[0,1],[1,2],[2,3],[3,4],[4,0]],[0,1,2,3,4],'The two-action experiment computes an exact expected-reward gradient; frontier algorithms and rollout pipelines are more complex.'),
12:S('Inside prompt construction',[
N('Task instruction','records',[-4,1,-1],'Specify what the model should produce and for whom.','task + constraints'),
N('Examples','pairs',[-4,-1,2],'Optional examples demonstrate an input-to-output pattern.','few-shot demonstrations'),
N('Output contract','matrix',[0,1,-1],'Define the required fields or prose structure. A format constraint alone does not ensure correctness.','schema or format description'),
N('Assembled prompt','tokens',[0,-1,2],'Combine the selected instruction, examples and output contract into input context.','ordered prompt text'),
N('Inference + validation','network',[4,0,0],'Run the model and check its response against the task and output contract. This demo assembles text only.','response → checks')],[[0,3],[1,3],[2,3],[3,4]],[0,1,2,3,4],'Prompting influences a forward pass; it does not perform training or guarantee factual answers.'),
13:S('Inside the context window',[
N('Instructions','records',[-4,1,-1],'Keep the task and behavior constraints available.','instruction tokens'),
N('History & memory','records',[-4,-1,2],'Select relevant recent turns or retrieved external notes.','selected past information'),
N('Evidence & tool results','graph',[0,1,-1],'Include useful evidence and actual tool observations.','retrieved material'),
N('Context selection','filter',[0,-1,2],'Fit selected material into a finite budget. Dropping or summarizing can lose information.','curated input sequence'),
N('Model call','network',[4,0,0],'Send the resulting context into inference. External memory matters only when accessed or included.','context → activations')],[[0,3],[1,3],[2,3],[3,4]],[0,1,2,3,4],'Adjust the token budget to see what fits. Counts are deliberately illustrative.'),
14:S('Inside retrieval-augmented generation',[
N('Documents → index','records',[-4,1,-1],'Chunk documents and build a retrieval index before answering queries.','chunks + identifiers'),
N('User query','tokens',[-4,-1,2],'Represent the information need as a query for the retriever.','query terms or vector'),
N('Retriever','matrix',[0,1,-1],'Select candidate chunks by lexical, vector or hybrid relevance. This lab uses lexical matching.','ranked candidate chunks'),
N('Evidence context','pairs',[0,-1,2],'Package selected passages with their document IDs into the model input.','query + supporting passages'),
N('Answer + support check','network',[4,0,0],'Generate an answer and verify that cited evidence supports it. Retrieval alone cannot prevent unsupported claims.','answer with traceable evidence')],[[0,2],[1,2],[2,3],[3,4]],[0,1,2,3,4],'Indexing is an offline preparation path; retrieval and generation are request-time operations.'),
15:S('Inside an agent’s action loop',[
N('Goal & current state','records',[-4,1,0],'Provide the task and observations so far. The local example asks for a calculation.','task + observations'),
N('Model decision','network',[-1,1,-1],'A model can propose a tool call or finish. The displayed trace is scripted for teaching.','structured action request'),
N('Tool executor','gpu',[2,1,-1],'Application code validates and executes the requested operation.','calculator result'),
N('Observation & check','loss',[4,-1,2],'Return the actual result and check it against the goal. An error can trigger another attempt.','verified observation'),
N('Update state or stop','merge',[-1,-1.5,2],'Append the observation, enforce the budget and either continue or return a result.','new context / final answer')],[[0,1],[1,2],[2,3],[3,4],[4,1]],[0,1,2,3,4],'This is an application feedback loop. It does not imply reinforcement learning or a weight update.'),
16:S('Inside graph-based systems',[
N('Request / source data','records',[-4,0,0],'Choose workflow mode for operations, or knowledge mode for entities and source relationships.','request or documents'),
N('Route / extract','split',[-1,0,0],'Workflow mode routes execution. Knowledge mode illustrates extracting named entities and relations.','condition or entity links'),
N('Branch / relationship A','graph',[2,1.5,-2],'A workflow branch performs an operation; a knowledge-graph edge records a relationship.','operation result or fact link'),
N('Branch / relationship B','graph',[2,-1.5,2],'Independent work can branch; entities can also have multiple relationships. These meanings are distinct.','second result or link'),
N('Merge / retrieve evidence','merge',[4,0,0],'Workflows merge outputs. Graph-based retrieval selects related evidence for a model response.','joined state or sourced context')],[[0,1],[1,2],[1,3],[2,4],[3,4]],[0,1,2,3,4],'Toggle the graph type. Read an edge as execution order only in workflow mode.'),
17:S('Inside a sparse expert layer',[
N('Token hidden vector','vector',[-4,0,0],'Route this token’s representation; different tokens may select different experts.','hidden vector'),
N('Learned router','split',[-1,0,0],'Score available experts and select a subset. The lab chooses the two highest invented scores.','routing scores → top 2'),
N('Expert group A','network',[2,1.5,-2],'Selected expert feed-forward networks transform the same incoming vector.','expert outputs'),
N('Expert group B','network',[2,-1.5,2],'Unselected experts stay inactive for this token in the toy sparse layer.','selected outputs only'),
N('Weighted combination','merge',[4,0,0],'Combine selected expert outputs using normalized routing weights.','mixed output → next operation')],[[0,1],[1,2],[1,3],[2,4],[3,4]],[0,1,2,3,4],'Top-2 routing across four toy experts is illustrative; routing policies differ between models.'),
18:S('Inside a multimodal input path',[
N('Image patches','image',[-4,1.5,-2],'An image is processed into spatial patches or visual features in this generic design.','image signal'),
N('Visual encoder + projector','network',[0,1.5,-2],'Convert visual information to compatible learned representations.','visual feature vectors'),
N('Text question','tokens',[-4,-1.5,2],'Tokenize and embed the associated question as language input.','text embeddings'),
N('Combine representations','merge',[1,-1,2],'Supply both modalities to the model. Exact fusion arrangements vary.','image features + text'),
N('Conditioned generation','network',[4,0,0],'Generate output conditioned on the available modalities. Visual errors remain possible.','answer tokens')],[[0,1],[1,3],[2,3],[3,4]],[0,1,2,3,4],'The geometry illustrates one common pattern, not the undisclosed internals of a particular frontier model.'),
19:S('Inside diffusion sampling',[
N('Initial noise','noise',[-4,1,0],'Sampling begins with a noise-like state in pixel or latent space.','noisy state xₜ'),
N('Condition + timestep','tokens',[-1.5,-1.5,2],'Provide the current noise level and optional text or other conditioning.','timestep + conditioning'),
N('Learned denoiser','network',[-1.5,1,-1],'A trained network predicts a noise-, data- or velocity-related quantity, depending on the objective.','predicted update quantity'),
N('Sampler update','noise',[1.5,1,-1],'The sampler uses that prediction to form a revised state, then repeats at another noise level.','xₜ → revised state'),
N('Decode final state','image',[4,0,1],'A latent model decodes the final latent representation into an image. Pixel-space models do not need this same latent decoder.','generated sample')],[[0,2],[1,2],[2,3],[3,2],[3,4]],[0,1,2,3,4],'The denoising slider controls a synthetic voxel interpolation, not a trained image generator.'),
20:S('Inside a reliability check',[
N('Held-out task','records',[-4,0,0],'Choose an independent task and define what a successful result means.','input + criteria'),
N('Candidate outputs','split',[-1,1.5,-2],'One or more attempts produce candidate results. Extra attempts consume inference resources.','candidate answers'),
N('Evidence / ground truth','records',[-1,-1.5,2],'Use appropriate reference material, exact outcomes or expert review.','independent check signal'),
N('Check + diagnose','loss',[2,0,0],'Test the candidates and distinguish generation, retrieval and tool failures.','pass / fail + reason'),
N('Accept or revise','merge',[4,0,1],'Return a supported result or revise the application and retest. A test result does not establish universal reliability.','checked result / next iteration')],[[0,1],[1,3],[2,3],[3,4],[4,1]],[0,1,2,3,4],'The lab checks a numeric answer exactly. It does not claim to automatically verify all natural-language facts.')
};
