import {createFoundations} from './foundations.js';
import {microScenes} from './chapters.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createExpansion(api){
let selected=0,flowAuto=false,flowClock=0,transition=0,priorCanvas=null,priorPoint=[0,0],scene=null,lastMode='',rlTheta=0,rlSteps=0,contextBudget=900,agentIndex=0,graphType='workflow',expertToken=0,noiseLevel=.7;
const state=()=>api.state(),C='#82e5b5',V='#b6a3ff',A='#f3bd71',B='#82bfff';
const foundations=createFoundations(api,setPart);
const world=$('.world');
world.insertAdjacentHTML('beforeend','<div id="partLabels"></div><div id="flowControl"><div class="flow-top"><span class="eyebrow mint">INSIDE THIS SUBSYSTEM</span><button id="flowPlay">▷ Play flow</button></div><div id="flowSteps"></div><div id="flowReadout" aria-live="polite"></div><div class="flow-bottom"><span id="flowPayload"></span><button id="flowNext">Next operation →</button></div></div>');
const docs=[{id:'D1',text:'A model learns by updating weights during training.'},{id:'D2',text:'Inference uses fixed weights to generate tokens from context.'},{id:'D3',text:'A GPU accelerates matrix operations and needs memory.'}];
function enter(){const st=state();scene=microScenes[st.current];world.classList.toggle('is-detail',!!scene);$('#flowControl').hidden=!scene;$('#partLabels').hidden=!scene;$('#sceneLabels').hidden=!!scene;flowAuto=false;flowClock=0;selected=0;transition=st.reduced?1:0;
if(scene){priorCanvas=document.createElement('canvas');priorCanvas.width=st.canvas.width;priorCanvas.height=st.canvas.height;priorCanvas.getContext('2d').drawImage(st.canvas,0,0);priorPoint=api.project(st.anchor).slice(0,2);$('.world-title .eyebrow').textContent='FULL SYSTEM / '+st.lesson.tag;$('.world-title h1').textContent=st.lesson.nav;$('.world-title p').textContent=scene.name;$('#partLabels').innerHTML=scene.nodes.map((n,i)=>`<button class="part-label" data-part="${i}"><span>${String(i+1).padStart(2,'0')}</span><strong>${n.label}</strong><small>${n.payload}</small></button>`).join('');$$('[data-part]').forEach(b=>b.onclick=()=>setPart(+b.dataset.part));$('#flowSteps').innerHTML=scene.nodes.map((n,i)=>`<button data-flow="${i}" aria-label="Inspect ${n.label}">${i+1}</button>`).join('');$$('[data-flow]').forEach(b=>b.onclick=()=>setPart(+b.dataset.flow));setPart(0);api.camera(true)}else{priorCanvas=null;$('.world-title .eyebrow').textContent='FROM FIRST PRINCIPLES TO GENERATIVE SYSTEMS';$('.world-title h1').innerHTML='Inside AI<span>.</span>';$('.world-title p').textContent='Understand the basics. Follow the data. Explore what comes next.';api.camera(false)}
}
function setPart(i,manual=true){if(!scene)return;selected=(i+scene.nodes.length)%scene.nodes.length;if(manual){flowAuto=false;flowClock=0}$('#flowPlay').textContent=flowAuto?'Ⅱ Pause flow':'▷ Play flow';const n=scene.nodes[selected];$('#flowReadout').innerHTML=`<strong>${selected+1}. ${n.label}</strong><p>${n.detail}</p>`;$('#flowPayload').textContent='PAYLOAD · '+payload(selected);$$('[data-part]').forEach((b,k)=>{b.classList.toggle('selected',k===selected);b.setAttribute('aria-pressed',String(k===selected))});$$('[data-flow]').forEach((b,k)=>{b.classList.toggle('active',k===selected);b.setAttribute('aria-pressed',String(k===selected))});}
$('#flowPlay').onclick=()=>{flowAuto=!flowAuto;if(flowAuto)api.resume();flowClock=0;$('#flowPlay').textContent=flowAuto?'Ⅱ Pause flow':'▷ Play flow'};$('#flowNext').onclick=()=>setPart(selected+1);
function payload(i){const st=state();const basic=foundations.payload(st.current,i);if(basic!==undefined)return basic;if(st.current===2){const tok=$$('#tokenOutput .token');if(i===0)return $('#tokenInput')?.value||'text';if(i===2)return tok.slice(0,5).map(t=>t.firstChild?.textContent).join(' · ');if(i===3||i===4)return tok.slice(0,6).map(t=>t.querySelector('small')?.textContent).join(' → ')||'empty sequence'}if(st.current===3&&i===2)return 'cat ↔ '+($('#vectorWord')?.value||'kitten');if(st.current===4)return `Block ${st.layer+1}/6 · ${scene.nodes[i].payload}`;if(st.current===6&&i===4)return '−ln(p) = '+($('#lossN')?.textContent||'1.386');if(st.current===7){if(i===0)return `ŷ = ${(2*st.trainW).toFixed(4)}`;if(i===2)return `dL/dw = ${(4*(2*st.trainW-4)).toFixed(4)}`;if(i===4)return `w = ${st.trainW.toFixed(4)}`}if(st.current===8)return `${st.gpuCount} GPUs · ${st.parallel} parallelism`;if(st.current===10&&i===4)return $('#generated')?.textContent||'new token';if(st.current===11&&i===0)return `π(A) = ${(100/(1+Math.exp(-rlTheta))).toFixed(1)}%`;if(st.current===17){const scores=[[.55,.25,.15,.05],[.1,.15,.6,.15],[.05,.2,.3,.45]][expertToken],on=[0,1,2,3].sort((a,b)=>scores[b]-scores[a]).slice(0,2);if(i===2||i===3)return [(i-2)*2,(i-2)*2+1].map(k=>`E${k+1}: ${on.includes(k)?'ACTIVE':'inactive'}`).join(' · ');if(i===1)return 'top 2 → '+on.map(k=>'E'+(k+1)).join(' + ')}if(st.current===13&&i===3)return `budget = ${contextBudget} illustrative tokens`;if(st.current===16)return graphType==='workflow'?['task: 12 × 3','route: numeric task','calculator branch','retrieval branch','joined workflow state'][i]:['source documents','entity + relationship extraction','Mira → leads → Atlas','Atlas → uses → GPU','source-linked evidence'][i];return scene.nodes[i].payload}
function mesh(n,i){if(foundations.mesh(n,i,selected))return;const st=state(),p=n.p,c=st.current>=10?A:st.current>=4?V:C;const color=i===selected?c:'#617d91',o=i===selected?.7:.34;const add=(v,size,co=color,op=o)=>api.cube([p[0]+v[0],p[1]+v[1],p[2]+v[2]],size,co,op);add([0,-.58,0],[1.8,.06,1.4],color,.18);
switch(n.type){
case'records':for(let k=0;k<5;k++)add([.08*k,-.2+k*.15,0],[1.35,.06,1.1]);break;
case'tokens':{const count=st.current===2?Math.max(1,Math.min(8,$$('#tokenOutput .token').length)):6;for(let k=0;k<count;k++)add([-.55+(k%3)*.5,-.12+Math.floor(k/3)*.35,0],[.34,.24,.55]);break}
case'matrix':for(let x=0;x<5;x++)for(let y=0;y<4;y++)add([-.6+x*.3,-.2+y*.26,0],[.2,.17,.35],(x+y)%3?color:B,o*((x+y)%3?.6:1));break;
case'network':if(st.current===17&&(i===2||i===3)){const scores=[[.55,.25,.15,.05],[.1,.15,.6,.15],[.05,.2,.3,.45]][expertToken],on=[0,1,2,3].sort((a,b)=>scores[b]-scores[a]).slice(0,2);for(let e=0;e<2;e++){const id=(i-2)*2+e;for(let k=0;k<3;k++)add([-.42+e*.84,-.2+k*.32,0],[.65,.13,.85],on.includes(id)?C:'#354957',on.includes(id)?.7:.13)}break}for(let l=0;l<4;l++){add([0,-.25+l*.34,0],[1.4,.06,1.1]);for(let k=0;k<4;k++)add([-.4+(k%2)*.8,-.1+l*.34,-.28+Math.floor(k/2)*.56],[.16,.17,.16])}break;
case'attention':for(let r=0;r<4;r++)for(let c=0;c<4;c++)add([-.6+c*.37,.3,-.55+r*.37],[.27,.12,.27],c>r?'#253644':color,c>r?.15:(st.current===5&&r===st.attnRow?.8:o));break;
case'gpu':for(let k=0;k<4;k++){const on=st.current!==8||k+(i===2?4:0)<st.gpuCount;add([-.5+(k%2)*.95,0,-.4+Math.floor(k/2)*.8],[.66,.22,.56],on?B:'#34424d',on?o:.15);add([-.5+(k%2)*.95,.16,-.4+Math.floor(k/2)*.8],[.29,.07,.25],on?'#c9e5ff':'#34424d',on?o:.12)}break;
case'bars':for(let k=0;k<5;k++){let h=.25+((k*7+2)%5)*.2;if(st.current===6)h=k===2?+(($('#prob')?.value)||25)/70:.3;if(st.current===11)h=k<2?(k===0?1/(1+Math.exp(-rlTheta)):1-1/(1+Math.exp(-rlTheta)))*1.5:.08;add([-.6+k*.3,-.35+h/2,0],[.21,h,.55])}break;
case'pairs':for(let k=0;k<3;k++){add([-.45,-.15+k*.3,0],[.5,.17,.7],C);add([.45,-.15+k*.3,0],[.5,.17,.7],A)}break;
case'filter':for(let k=0;k<4;k++)add([0,-.3+k*.32,0],[1.5-k*.27,.08,1.3-k*.2]);break;
case'loss':for(let k=0;k<5;k++)add([-.6+k*.3,-.3+(4-k)*.1,0],[.2,.12+(4-k)*.2,.5]);break;
case'split':add([-.6,0,0],[.35,.35,.5]);for(let k=0;k<3;k++)add([.6,-.3+k*.4,-.4+k*.4],[.35,.25,.35]);break;
case'merge':for(let k=0;k<3;k++)add([-.6,-.3+k*.4,-.4+k*.4],[.3,.25,.3]);add([.6,0,0],[.5,.5,.6]);break;
case'image':case'noise':for(let x=0;x<6;x++)for(let z=0;z<6;z++){const target=(x===z||x+z===5)?1:.1;const random=((x*7+z*13+3)%17)/17;const alpha=n.type==='noise'?noiseLevel:0;const h=.08+(random*alpha+target*(1-alpha))*.6;add([-.75+x*.3,-.2+h/2,-.75+z*.3],[.23,h,.23],target>.5?C:B,o)}break;
case'vector':add([0,0,0],[.18,.18,.18]);break;
case'graph':for(let k=0;k<6;k++)add([Math.cos(k*1.05)*.7,Math.sin(k*1.05)*.55,Math.sin(k*2.1)*.45],[.2,.2,.2]);break;
case'rings':for(let k=0;k<14;k++)add([Math.cos(k*Math.PI/7)*.68,Math.sin(k*Math.PI/7)*.4,Math.sin(k*Math.PI/7)*.6],[.1,.1,.1]);break;
}}
function ornaments(n,i){foundations.ornaments(n,i,selected);const st=state(),p=n.p,color=i===selected?(st.current>9?A:C):'#567888';if(n.type==='vector'){for(let k=0;k<3;k++){const v=[p[0]+.7-k*.2,p[1]+.8-k*.3,p[2]+k*.38];api.line3(p,v,color,2,.8);api.dot3(v,color,3,.9,true)}}if(n.type==='graph'){for(let k=0;k<6;k++){const a=[p[0]+Math.cos(k*1.05)*.7,p[1]+Math.sin(k*1.05)*.55,p[2]+Math.sin(k*2.1)*.45],b=[p[0]+Math.cos((k+2)*1.05)*.7,p[1]+Math.sin((k+2)*1.05)*.55,p[2]+Math.sin((k+2)*2.1)*.45];api.line3(a,b,color,1,.6)}}if(n.type==='network'){for(let k=0;k<3;k++){const x=p[0]-.45+k*.45;api.line3([x,p[1]-.3,p[2]],[x,p[1]+1,p[2]],color,1,.4);api.dot3([x,p[1]-.3+(st.tick*.6+k*.2)%1.3,p[2]],color,2.5,.8,true)}}}
function render(dt){if(!scene)return;const st=state(),{ctx,W,H}=st;transition=Math.min(1,transition+dt*1.5);if(flowAuto&&st.playing){flowClock+=dt;if(flowClock>4.5){flowClock=0;setPart(selected+1,false)}}ctx.clearRect(0,0,W,H);for(let k=-8;k<9;k++){api.line3([k,-2.4,-5],[k,-2.4,5],'#34515e',.6,.19);api.line3([-8,-2.4,k],[8,-2.4,k],'#34515e',.6,.19)}
const localEdges=st.current===8&&st.parallel==='pipeline'?[[0,1],[1,2],[2,3],[3,4]]:scene.edges;localEdges.forEach(([a,b],ei)=>{const na=scene.nodes[a],nb=scene.nodes[b],active=(b===selected||a===selected)&&!(st.current===16&&graphType==='workflow'&&(a===3||b===3)),returning=b<a,c=returning?V:(st.current>=10?A:C),lift=returning?1.5:.3;let prev=na.p;for(let j=1;j<=25;j++){const next=api.path(na.p,nb.p,j/25,lift);api.line3(prev,next,c,active?1.8:1,active?.6:.16);prev=next}if(active)for(let j=0;j<3;j++)api.dot3(api.path(na.p,nb.p,(st.tick*.18+j/3+ei*.12)%1,lift),c,3,.95,true);const q=api.project(api.path(na.p,nb.p,.72,lift)),r=api.project(api.path(na.p,nb.p,.66,lift)),ang=Math.atan2(q[1]-r[1],q[0]-r[0]);ctx.beginPath();ctx.moveTo(q[0]-7*Math.cos(ang-.5),q[1]-7*Math.sin(ang-.5));ctx.lineTo(q[0],q[1]);ctx.lineTo(q[0]-7*Math.cos(ang+.5),q[1]-7*Math.sin(ang+.5));ctx.strokeStyle=api.rgba(c,active?.9:.3);ctx.lineWidth=1.5;ctx.stroke()});
api.clearFaces();scene.nodes.forEach(mesh);api.flushFaces();scene.nodes.forEach(ornaments);const placed=[];const ordered=scene.nodes.map((n,i)=>({n,i})).sort((a,b)=>(b.i===selected)-(a.i===selected));for(const {n,i} of ordered){const p=api.project(n.p),b=$(`[data-part="${i}"]`);const width=W<550?112:W<900?135:165;b.style.maxWidth=width+'px';b.querySelector('small').textContent=payload(i);if(st.current===16)b.querySelector('strong').textContent=(graphType==='workflow'?['Task','Conditional router','Calculator','Document retrieval','Merge state']:['Source documents','Extract entities','Mira → leads → Atlas','Atlas → uses → GPU','Evidence retrieval'])[i];const bw=b.offsetWidth||width,bh=b.offsetHeight||48,top=180,bottom=H-($('#flowControl').offsetHeight||220)-43;const candidates=[];for(const dy of [30,-58,78,-106,126])for(const dx of [0,-45,45,-90,90])candidates.push({x:Math.max(bw/2+8,Math.min(W-bw/2-8,p[0]+dx)),y:Math.max(top,Math.min(bottom-bh,p[1]+dy)),cost:Math.abs(dx)+Math.abs(dy-30)});for(let y=top;y<bottom-bh;y+=48)for(let x=bw/2+8;x<W-bw/2;x+=bw+10)candidates.push({x,y,cost:200+Math.abs(x-p[0])+Math.abs(y-p[1])});const fits=c=>!placed.some(r=>Math.abs(r.x-c.x)<(r.w+bw)/2+6&&c.y<r.y+r.h+5&&c.y+bh+5>r.y);candidates.sort((a,b)=>a.cost-b.cost);const spot=candidates.find(fits)||candidates[0];b.style.left=spot.x+'px';b.style.top=spot.y+'px';b.style.opacity=String(.65+.35*transition);placed.push({...spot,w:bw,h:bh});ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(spot.x,spot.y+bh/2);ctx.strokeStyle=api.rgba(i===selected?C:'#547282',i===selected?.55:.23);ctx.lineWidth=.7;ctx.stroke();}api.setHits(scene.nodes.map((n,i)=>{const p=api.project(n.p);return {x:p[0],y:p[1],i,r:30,part:true}}));$('#flowPayload').textContent='PAYLOAD · '+payload(selected);
if(priorCanvas&&transition<1){ctx.save();ctx.globalAlpha=(1-transition)**2;const scale=1+transition*1.6;ctx.translate(W/2+(priorPoint[0]-W/2)*(1-transition),H*.5+(priorPoint[1]-H*.5)*(1-transition));ctx.scale(scale,scale);ctx.drawImage(priorCanvas,-priorPoint[0],-priorPoint[1],W,H);ctx.restore()}else priorCanvas=null;
}
function labHTML(kind){const basic=foundations.labHTML(kind);if(basic)return basic;const p=(title,body)=>`<h3>${title}</h3>${body}`;switch(kind){
case'rl':return p('Optimize a two-action policy','<p>A earns reward 1; B earns reward 0. We optimize exact expected reward J = P(A), using a logistic policy.</p><div class="statrow"><div class="stat"><strong id="rlProb"></strong><small>P(A), reward = 1</small></div><div class="stat"><strong id="rlReward"></strong><small>Expected reward J</small></div></div><button id="rlTrain" class="primary">Apply policy-gradient update ↻</button><button id="rlReset" class="secondary">Reset policy</button><p id="rlNote" aria-live="polite"></p><p>θ ← θ + 0.8 × p(1−p). Exact expectation over two actions; no sampled estimator, baseline, KL penalty or frontier algorithm is implemented.</p>');
case'prompting':return p('Build an instruction','<label for="promptTask">Task</label><select id="promptTask"><option>Summarize the supplied passage</option><option>Extract dates from the supplied passage</option></select><label><input type="checkbox" id="promptExample" checked> Include one example</label><label><input type="checkbox" id="promptSchema" checked> Specify the output format</label><div class="generated" id="builtPrompt"></div><p>Prompt assembly only. No claim is made that an added example always improves the answer.</p>');
case'context':return p('Fit a finite context budget','<label for="contextBudget">Illustrative token budget: <span id="contextN">900</span></label><input id="contextBudget" type="range" min="250" max="1600" step="50" value="900"><div class="flow-list" id="contextItems"></div><p id="contextNote"></p><p>Fixed priority: instructions, task, evidence, history, older tool output. A real selection strategy should be evaluated for the task.</p>');
case'rag':return p('Retrieve from three tiny documents','<label for="retrievalQuery">Query</label><select id="retrievalQuery"><option>training weights</option><option>inference context</option><option>GPU matrix memory</option><option>ocean temperature</option></select><div id="retrievalResults"></div><p>Exact lowercase word overlap ranks these local documents. This lab performs retrieval only; it does not generate an answer.</p>');
case'agent':return p('Trace a tool-assisted calculation','<p>Task: calculate 12 × 3, then add 4.</p><div class="generated" id="agentTrace" aria-live="polite"></div><button id="agentNext" class="primary">Advance the action loop →</button><button id="agentReset" class="secondary">Restart trace</button><p>This is a scripted application trace using real local arithmetic. The numeric result comes from execution, not a model’s claim.</p>');
case'graphs':return p('Switch the graph’s meaning','<label for="graphType">Graph type</label><select id="graphType"><option value="workflow">Workflow  ·  execution paths</option><option value="knowledge">Knowledge  ·  entity relationships</option></select><div class="flow-list" id="graphLegend"></div><p id="graphNote"></p>');
case'moe':return p('Inspect top-2 routing','<label for="expertToken">Illustrative token representation</label><select id="expertToken"><option value="0">Token A</option><option value="1">Token B</option><option value="2">Token C</option></select><div class="bars" id="expertBars"></div><p id="expertNote"></p>');
case'multimodal':return p('Inspect the input paths','<label for="modality">Highlight a modality</label><select id="modality"><option value="image">Image → visual features</option><option value="text">Text → token embeddings</option><option value="combined">Combined → answer</option></select><div class="callout" id="modalityNote"></div><p>The voxel image is a schematic patch grid. It is not an actual encoded image or a live vision model.</p>');
case'diffusion':return p('Move along a denoising trajectory','<label for="noiseLevel">Illustrative noise mixture: <span id="noiseN">70%</span></label><input id="noiseLevel" type="range" min="0" max="100" value="70"><p>Move toward 0% to reveal a simple pattern in the 3D voxel grid. The slider interpolates synthetic values; it does not evaluate a denoising network.</p>');
case'eval':return p('Check candidate answers exactly','<p>Task: (12 × 3) + 4 = ?</p><label for="candidate">Candidate answer</label><select id="candidate"><option value="40">40</option><option value="39">39</option><option value="44">44</option></select><button id="checkAnswer" class="primary">Run numeric check</button><div class="callout" id="evalNote" aria-live="polite">Select an answer and compare it with the independently computed result.</div><p>This exact arithmetic check says nothing about other tasks or free-text factual accuracy.</p>');
}}
function bindLab(){foundations.bindLab();if($('#rlTrain')){const f=()=>{const p=1/(1+Math.exp(-rlTheta));$('#rlProb').textContent=(100*p).toFixed(1)+'%';$('#rlReward').textContent=p.toFixed(3);$('#rlNote').textContent=`Update ${rlSteps} · θ = ${rlTheta.toFixed(4)} · dJ/dθ = ${(p*(1-p)).toFixed(4)}`};$('#rlTrain').onclick=()=>{const p=1/(1+Math.exp(-rlTheta));rlTheta+=.8*p*(1-p);rlSteps++;f();setPart(4)};$('#rlReset').onclick=()=>{rlTheta=0;rlSteps=0;f();setPart(0)};f()}
if($('#promptTask')){const f=()=>{const dates=$('#promptTask').value.startsWith('Extract');$('#builtPrompt').textContent=`Task: ${$('#promptTask').value}. Use only the supplied passage.`+($('#promptExample').checked?(dates?' Example: “Meet on 6 May.” → [“6 May”].':' Example: “Rain closed the road.” → “Road closed by rain.”'):'')+($('#promptSchema').checked?(dates?' Return a JSON array of date strings.':' Return one sentence of at most 20 words.'):'');};$('#promptTask').onchange=f;$('#promptExample').onchange=f;$('#promptSchema').onchange=f;f()}
if($('#contextBudget')){const f=()=>{contextBudget=+$('#contextBudget').value;$('#contextN').textContent=contextBudget;let used=0;const items=[['Instructions',150],['Current task',100],['Relevant evidence',450],['Recent history',350],['Older tool output',400]];$('#contextItems').innerHTML=items.map(([name,n])=>{const fit=used+n<=contextBudget;if(fit)used+=n;return `<div>${name} · ${n}<em>${fit?'INCLUDED':'DOES NOT FIT'}</em></div>`}).join('');$('#contextNote').textContent=`${used} / ${contextBudget} tokens used. Omitted material will not be available in this model call.`};$('#contextBudget').oninput=f;f()}
if($('#retrievalQuery')){const f=()=>{const q=$('#retrievalQuery').value.toLowerCase().split(' ');const ranked=docs.map(d=>({...d,score:q.filter(t=>d.text.toLowerCase().match(/\b\w+\b/g).includes(t)).length})).sort((a,b)=>b.score-a.score);$('#retrievalResults').innerHTML=ranked[0].score?ranked.filter(d=>d.score).map(d=>`<div class="callout"><strong>${d.id} · ${d.score} matching terms</strong>${d.text}</div>`).join(''):'<div class="callout">No lexical match. This small index supplies no supporting passage for this query.</div>';setPart(2)};$('#retrievalQuery').onchange=f;f()}
if($('#agentNext')){agentIndex=0;const trace=['State: compute (12 × 3) + 4. No tool observation yet.','Request: calculator.multiply(12, 3). Application validates the arguments.',`Observation: multiply returned ${12*3}. Add this result to the context.`,'Request: calculator.add(36, 4). Application validates the arguments.',`Observation: add returned ${36+4}. Verify the task is complete.`,'Stop: return 40. Two local tool operations completed.'];const f=()=>{$('#agentTrace').textContent=trace[agentIndex];$('#agentNext').disabled=agentIndex===trace.length-1;setPart([0,1,3,1,3,4][agentIndex])};$('#agentNext').onclick=()=>{agentIndex=Math.min(trace.length-1,agentIndex+1);f()};$('#agentReset').onclick=()=>{agentIndex=0;f()};f()}
if($('#graphType')){const f=()=>{graphType=$('#graphType').value;$('#graphLegend').innerHTML=(graphType==='workflow'?['Nodes = operations','Edges = execution paths','Branch = a runtime condition','Merge = combined state']:['Nodes = entities','Edges = named relationships','Mira → leads → Atlas','Atlas → uses → GPU']).map(t=>`<div>${t}</div>`).join('');$('#graphNote').textContent=graphType==='workflow'?'Numeric requests follow a calculator route; document questions follow retrieval. The topology describes control flow.':'These are invented facts for teaching graph structure. A real knowledge graph needs source provenance. The topology describes relationships.';setPart(1)};$('#graphType').onchange=f;f()}
if($('#expertToken')){const f=()=>{expertToken=+$('#expertToken').value;const scores=[[.55,.25,.15,.05],[.1,.15,.6,.15],[.05,.2,.3,.45]][expertToken],indices=[0,1,2,3].sort((a,b)=>scores[b]-scores[a]).slice(0,2),sum=indices.reduce((s,i)=>s+scores[i],0);$('#expertBars').innerHTML=scores.map((p,i)=>`<div class="barline"><span>E${i+1}${indices.includes(i)?' ✓':''}</span><div class="bartrack"><div class="barfill" style="width:${p*100}%;background:${indices.includes(i)?C:'#486171'}"></div></div><span>${p.toFixed(2)}</span></div>`).join('');$('#expertNote').textContent='Active: '+indices.map(i=>`E${i+1} at ${(scores[i]/sum*100).toFixed(1)}% combination weight`).join(' + ')+'. Scores are illustrative.';setPart(1)};$('#expertToken').onchange=f;f()}
if($('#modality')){const f=()=>{const value=$('#modality').value;setPart(value==='image'?1:value==='text'?2:3);$('#modalityNote').textContent=value==='image'?'Image patches → visual encoder → projected feature vectors.':value==='text'?'Question text → tokenizer → embedding lookup.':'Visual and text representations condition the model’s answer together.'};$('#modality').onchange=f;f()}
if($('#noiseLevel')){$('#noiseLevel').oninput=()=>{noiseLevel=+$('#noiseLevel').value/100;$('#noiseN').textContent=Math.round(noiseLevel*100)+'%';setPart(3)};noiseLevel=.7}
if($('#checkAnswer')){$('#checkAnswer').onclick=()=>{const result=(12*3)+4,value=+$('#candidate').value;$('#evalNote').textContent=value===result?`Pass: ${value} matches independently computed ${result}. This candidate passes this arithmetic check.`:`Fail: ${value} differs from independently computed ${result}. Revise this candidate before accepting it.`;setPart(3)};$('#candidate').onchange=()=>$('#evalNote').textContent='Candidate changed. Run the numeric check again.'}
}
return {enter,render,setPart,labHTML,bindLab,hasScene:()=>!!scene};
}
