// Foundations extend the existing lesson IDs without moving any original chapter.
export const foundationLessons = [
{nav:'What is AI?',title:'A machine can solve a task.<br>That does not make it human.',tag:'FOUNDATIONS',intro:'Artificial intelligence is the broad field of building systems that perform tasks such as recognizing patterns, reasoning, planning and generating content. Some AI follows rules written by people. Some learns from examples.',key:'AI is the umbrella',take:'Machine learning is part of AI. Deep learning is part of machine learning and uses neural networks with many layers. Generative AI describes a kind of task: creating content.',lab:'aiBasics',deep:'An everyday example: sorting messages',body:'A rule system might flag a message if it contains a particular phrase. A machine-learning classifier can learn patterns from labeled messages. A generative model can draft a reply. These are different jobs, even when they appear inside the same app.',extra:'What the nested model means',more:'The nested frames show a relationship between fields, not stages that every input passes through. Neural networks are one machine-learning family; decision trees and linear models are others. Deep networks can classify as well as generate. Good performance on one task does not establish consciousness, human-like understanding or competence on every task.'},
{nav:'Machine learning',title:'Show examples.<br>Fit a reusable pattern.',tag:'FOUNDATIONS',intro:'Machine learning fits a model using data so it can make predictions or decisions on new inputs. Instead of writing every rule yourself, you choose a model, a learning objective and a way to update its parameters.',key:'Learning must transfer',take:'Fitting the examples is only part of the job. Test on examples kept out of training to see whether the pattern generalizes.',lab:'machineLearning',deep:'Try learning a simple relationship',body:'Imagine estimating how far a toy cart travels from the number of motor pulses. Our invented training pairs are (1, 2), (2, 4) and (3, 6). The model predicts distance = weight × pulses. A gradient step adjusts that one weight to reduce mean squared error. The held-out pair (4, 8) never contributes to its gradient.',formula:'prediction = w × x; loss = mean((prediction − target)²)',extra:'Different learning signals',more:'Supervised learning uses targets, such as known distances or spam labels. Unsupervised learning seeks structure without those labels. Self-supervised learning constructs targets from the data itself, as in next-token training. Reinforcement learning uses rewards from actions or outcomes. Training and evaluation data can differ from real use, so a good test score is useful evidence, not a guarantee.'},
{nav:'Neural networks',title:'Small calculations.<br>Connected into a network.',tag:'FOUNDATIONS',intro:'An artificial neuron takes numbers, multiplies each by a weight, adds a bias, then applies an activation function. Connecting many of these units creates a neural network. It is a mathematical model, not a biological brain.',key:'Weights control influence',take:'A positive weight increases the sum as its input rises. A negative weight decreases it. An activation such as ReLU introduces a bend that helps networks represent nonlinear patterns.',lab:'neuron',deep:'One neuron, with real arithmetic',body:'Use two toy signals: light level and motion level. This neuron computes z = w₁ × light + w₂ × motion + bias, then outputs max(0, z). Change the light weight and watch its contribution, the sum and the output change in the 3D flow. These hand-set values do not form a trained detector.',formula:'z = w₁x₁ + w₂x₂ + b; ReLU(z) = max(0, z)',extra:'From one neuron to learning',more:'A layer contains many units, and later layers use earlier outputs. Training adjusts weights and biases using a loss, backpropagation and an optimizer. Activations change on each forward pass. A single ReLU output is neither a probability nor a verdict. Networks can also use other activation functions.'},
{nav:'Deep learning',title:'Build representations<br>one layer at a time.',tag:'FOUNDATIONS',intro:'Deep learning uses neural networks with multiple layers to learn useful representations. Each layer transforms the previous one. In image recognition, early layers can respond to local contrasts while later layers combine features.',key:'Depth composes operations',take:'Nonlinear layers can build complex functions from simpler ones. Adding depth alone does not guarantee better results. Data, architecture and training all matter.',lab:'deepLearning',deep:'Watch a tiny pattern become features',body:'This hand-built image example has a 4 × 4 input. ReLU differences between neighboring pixels detect contrast in two directions. Averaging those differences gives two features. Their relative sizes distinguish a vertical split, horizontal split, mixed edges or a blank field. The colored grids and scores come from these exact local calculations.',extra:'A teaching circuit, not a trained vision model',more:'This fixed feature pipeline illustrates successive representations. It does not learn, recognize objects or show measured activations from a production network. Real convolutional networks learn filters; vision Transformers commonly process patch representations with attention. Deep learning supports classifiers, language models, diffusion models and world models, with different architectures and objectives.'},
{nav:'Matrix multiplication',title:'Multiply matched numbers.<br>Add the results.',tag:'FOUNDATIONS',intro:'A matrix is a rectangular table of numbers. Matrix multiplication combines each row of the first table with each column of the second. It lets a computer perform many weighted sums in one organized operation.',key:'Row meets column',take:'For A shaped m × k and B shaped k × n, the result has shape m × n. The inner sizes must match. Matrix multiplication is different from multiplying matching cells element by element.',lab:'matrixMath',deep:'Two baskets, two price lists',body:'Basket A holds 2 apples and 1 orange. Basket B holds 1 apple and 3 oranges. Two shops price those fruits differently. Multiply the basket quantities by the price table to find four totals. Select a result cell to highlight the matching row, column and two products in 3D.',formula:'Cᵢⱼ = Σₖ AᵢₖBₖⱼ',extra:'Why neural networks and GPUs care',more:'A layer can multiply a batch of input vectors by a learned weight matrix, then add biases and apply an activation. GPUs divide matrix work into tiles and execute many arithmetic operations in parallel. This lab uses ordinary local arithmetic, not a GPU benchmark. An evaluation metric is a score such as accuracy or loss; the operation here is matrix multiplication.'},
{nav:'World models',title:'Imagine what happens next.<br>Check it against the world.',tag:'PREDICTION & PLANNING',intro:'A world model predicts how an environment may change. In an action-conditioned model, that prediction depends on the current state and a proposed action. A planner or policy can use predicted outcomes to help choose what to do.',key:'Prediction and decision are different jobs',take:'The world model estimates consequences. A policy or planner chooses actions. The environment supplies observations that reveal where predictions were wrong.',lab:'worldModel',deep:'A cart that learns how far it moves',body:'Our toy environment moves a cart 1.2 units per motor pulse. Three recorded transitions teach a one-parameter dynamics model its movement scale. Before fitting, that scale is wrong. Try different actions and prediction horizons, then compare the imagined endpoint with the actual toy environment. Longer rollouts amplify the scale error.',formula:'predicted next position = position + learned scale × action',extra:'What world models do and do not imply',more:'Learned world models can represent images, compact latent states or other signals. Model-based reinforcement learning can use imagined trajectories for planning or policy training. Prediction errors and unfamiliar situations can undermine those trajectories. A convincing video alone does not prove reliable physics or causal understanding. This exact cart simulation is a narrow teaching example, not a neural world model or a description of every frontier AI system.'}
];
const N=(label,type,p,detail,payload)=>({label,type,p,detail,payload});
const S=(name,nodes,edges,note)=>({name,nodes,edges,steps:nodes.map((_,i)=>i),note});
const top=[[-4,1,-1],[-1.5,1,-1],[1.5,1,-1],[4,1,0],[1.5,-1.5,2],[-1.5,-1.5,2]];
export const foundationScenes={
22:S('An umbrella of methods, three everyday jobs',[
N('AI → ML → deep learning','family',[-3.5,.4,0],'Nested frames mean inclusion: deep learning belongs to machine learning, which belongs to AI. These are fields, not a processing pipeline.','fields within fields'),
N('An incoming message','records',[0,1.4,-1.6],'A message can be checked against a rule, classified by a learned model or supplied to a generator. Pick an example in the experiment.','one task input'),
N('Rules written by people','filter',[3.5,1.4,-1.6],'A simple symbolic rule can make a decision without training on examples. This branch checks for a fixed phrase.','explicit rule → flag'),
N('A learned model','network',[0,-1.1,2],'A trained model can classify a message or generate a response. Its architecture and objective depend on the task.','learned patterns → output'),
N('Inspect the result','pairs',[3.5,-1.1,2],'Check a flag against a label or a drafted reply against the task and evidence. Output quality needs evaluation.','prediction or generated content')],[[1,2],[1,3],[2,4],[3,4]],'Frames show field membership. Arrows show two possible processing routes.'),
23:S('Fit on three examples, test on a fourth',[
N('Training examples','samples',top[0],'Use pulse counts 1, 2 and 3 with distances 2, 4 and 6. The held-out point stays outside the training objective.','(1,2), (2,4), (3,6)'),
N('Predict with w × x','fit',top[1],'The current weight sets the slope of a line through the origin. Every prediction is calculated from that weight.','three predictions'),
N('Measure training error','loss',top[2],'Average the three squared differences. Compute the gradient from these three training pairs only.','mean squared error'),
N('Update the weight','vector',top[3],'Subtract learning rate × gradient. The update changes the reusable model, not the data points.','w ← w − 0.05 × gradient'),
N('Held-out evaluation','holdout',top[4],'Predict distance for four pulses and compare with 8. This pair measures fit outside training; it supplies no update.','unseen input x = 4'),
N('Use the fitted model','bars',top[5],'The resulting slope can make new predictions. Success on this clean toy relationship does not prove general reliability.','new input → predicted distance')],[[0,1],[1,2],[2,3],[3,1],[1,4],[4,5]],'Mint points train the model. The amber point is held out.'),
24:S('Two inputs become one activation',[
N('Input signals','signals',top[0],'Light and motion are numeric inputs, scaled from 0 to 1. Change them in the lesson controls.','x = [light, motion]'),
N('Weighted contributions','contributions',top[1],'Multiply each input by its own weight. A negative weight subtracts from the total.','w₁x₁ and w₂x₂'),
N('Add a bias','bias',top[2],'Add both contributions and the bias, which shifts the activation threshold.','z = w₁x₁ + w₂x₂ + b'),
N('ReLU activation','relu',top[3],'Keep a positive sum. Replace a negative sum with zero. This bend makes the transformation nonlinear.','a = max(0, z)'),
N('Pass the activation onward','output', [0,-1.5,2],'This activation can feed many units in the next layer. It is not inherently a probability or a human-like thought.','one numerical output')],[[0,1],[1,2],[2,3],[3,4]],'Every value updates from the actual inputs and weights in this toy neuron.'),
25:S('A four-by-four pattern becomes two features',[
N('Pixel values','pixels',top[0],'Choose a pattern. Each of the sixteen cells is exactly 0 or 1. The grid contains no real-world image.','4 × 4 input'),
N('Local edge responses','features',top[1],'Compute absolute neighboring differences using two ReLUs: max(0,a−b) + max(0,b−a).','horizontal / vertical differences'),
N('Pool the responses','pooled',top[2],'Average each directional difference map into a feature. Pooling compresses the representation and loses spatial detail.','two edge averages'),
N('Compare the features','featureScores',top[3],'Compare left-right and up-down contrast. These are deterministic feature scores, not probabilities.','two scores'),
N('Describe the pattern','output',[0,-1.5,2],'More left-right contrast suggests a vertical boundary; more up-down contrast suggests a horizontal boundary. Equal nonzero scores mean mixed edges.','a simple pattern label')],[[0,1],[1,2],[2,3],[3,4]],'This is a hand-built feature hierarchy, not the internals of a trained model.'),
26:S('Two baskets × two shops = four exact totals',[
N('Quantities A','matrixA',[-3,1,-1.4],'Rows are baskets, columns are apples and oranges. Select a result to light up its entire input row.','A = [[2,1],[1,3]]'),
N('Prices B','matrixB',[0,1,-1.4],'Rows are fruits, columns are shops. The chosen output selects one shop column.','B = [[3,4],[2,1]]'),
N('Pairwise products','products',[3,1,-1.4],'Match apple quantity with apple price, and orange quantity with orange price. Multiply the two pairs independently.','two matched products'),
N('Add the products','sum',[3,-1.3,2],'Add the products to compute one basket total at one shop. This sum is a dot product.','one exact dot product'),
N('Result matrix C','matrixC',[-1,-1.3,2],'Repeat for all four row-column combinations. Quantities 2×2 times prices 2×2 gives four totals in a 2×2 matrix.','C = A × B')],[[0,2],[1,2],[2,3],[3,4]],'Mint selects a row. Violet selects a column. Amber marks their result.'),
27:S('A learned dynamics rule, imagined futures and a reality check',[
N('Recorded transitions','transitions',top[0],'Each example records an action and its observed displacement. Fitting these transitions learns a scale, not a policy.','action → observed change'),
N('Current state + action','action',top[1],'Start the cart at position zero. Choose backward, stay or forward as the action to repeat.','position + motor command'),
N('Learned dynamics','dynamics',top[2],'Predict displacement from action times the learned scale. Fit the scale using the recorded transitions.','predicted state transition'),
N('Imagined rollout','rollout',top[3],'Apply the predicted transition repeatedly for the chosen horizon. These positions are imagined, not fresh observations.','possible future positions'),
N('Environment observation','reality',top[4],'Run the same actions in the separate toy environment, which uses a fixed movement scale of 1.2.','observed endpoint'),
N('Compare and collect','discrepancy',top[5],'Measure endpoint error. New observations can later become training data. Comparing alone does not update weights.','prediction error')],[[0,2],[1,2],[2,3],[1,4],[3,5],[4,5],[5,0]],'The model predicts. You choose the action. The environment checks the prediction.')
};
export const trainingPairs=[[1,2],[2,4],[3,6]];
export function regression(w){const loss=trainingPairs.reduce((s,[x,y])=>s+(w*x-y)**2,0)/3;const gradient=trainingPairs.reduce((s,[x,y])=>s+2*x*(w*x-y),0)/3;return {loss,gradient,next:w-.05*gradient,heldout:(4*w-8)**2};}
export function neuronValue(light,motion,weight,bias){const terms=[light*weight,motion*.8],z=terms[0]+terms[1]+bias;return {terms,z,a:Math.max(0,z)};}
export function matrixProduct(A,B){if(!A.length||!B.length||A[0].length!==B.length)throw Error('Inner matrix dimensions must match');return A.map(row=>B[0].map((_,j)=>row.reduce((s,x,k)=>s+x*B[k][j],0)));}
export function featureModel(kind){const grid=Array.from({length:4},(_,r)=>Array.from({length:4},(_,c)=>kind==='vertical'?+(c>=2):kind==='horizontal'?+(r>=2):kind==='checker'?(r+c)%2:0));const dx=grid.map(row=>row.slice(1).map((v,c)=>Math.max(0,v-row[c])+Math.max(0,row[c]-v)));const dy=grid.slice(1).map((row,r)=>row.map((v,c)=>Math.max(0,v-grid[r][c])+Math.max(0,grid[r][c]-v)));const scores=[dx.flat(),dy.flat()].map(a=>a.reduce((s,v)=>s+v,0)/a.length);const label=scores[0]===0&&scores[1]===0?'No edges':scores[0]===scores[1]?'Mixed edges':scores[0]>scores[1]?'Vertical boundary':'Horizontal boundary';return {grid,dx,dy,scores,label};}
export const transitions=[[-1,-1.2],[1,1.2],[2,2.4]];
export function fitDynamics(){return transitions.reduce((s,[a,d])=>s+a*d,0)/transitions.reduce((s,[a])=>s+a*a,0);}
export function worldRollout(scale,action,horizon){return {predicted:Array.from({length:horizon+1},(_,t)=>t*scale*action),actual:Array.from({length:horizon+1},(_,t)=>t*1.2*action),error:Math.abs((scale-1.2)*action*horizon)};}
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmt=n=>Math.abs(n)<.00001?'0':Number(n.toFixed(3)).toString();
export function createFoundations(api,setPart){
let w=.4,steps=0,light=.6,motion=.5,weight=1,bias=-.4,pattern='vertical',cell=0,apple=3,scale=.7,action=1,horizon=3,example='classifier';
const A=[[2,1],[1,3]],B=()=>[[apple,4],[2,1]],nv=()=>neuronValue(light,motion,weight,bias),fv=()=>featureModel(pattern),wv=()=>worldRollout(scale,action,horizon);
const intro=(name,body)=>`<div class="foundation-lab"><div class="eyebrow mint">PLAY TO UNDERSTAND</div><h3>${name}</h3>${body}</div>`;
function labHTML(kind){switch(kind){
case'aiBasics':return intro('One input, different kinds of AI','<label for="aiExample">Choose an everyday system</label><select id="aiExample"><option value="rule">A rule flags a phrase</option><option value="classifier" selected>A model classifies a message</option><option value="generator">A language model drafts a reply</option></select><div id="aiMembership" class="concept-pills"></div><div class="callout" id="aiExampleNote" aria-live="polite"></div><p>These examples explain categories. This experiment does not run a classifier or a language model.</p>');
case'machineLearning':return intro('Teach a cart’s distance model','<div class="example-pairs"><span>1 pulse → 2 units</span><span>2 pulses → 4 units</span><span>3 pulses → 6 units</span></div><div class="statrow"><div class="stat"><strong id="mlWeight"></strong><small>Learned slope</small></div><div class="stat"><strong id="mlLoss"></strong><small>Training MSE</small></div></div><button id="mlTrain" class="primary">Learn from these examples ↻</button><button id="mlReset" class="secondary">Reset the weight</button><div id="mlTest" class="callout" aria-live="polite"></div><p>Exact gradient descent at learning rate 0.05. The amber test point never enters the update.</p>');
case'neuron':return intro('Tune a single neuron','<label for="nnLight">Light signal: <span id="nnLightN"></span></label><input id="nnLight" type="range" min="0" max="1" step=".1" value=".6"><label for="nnMotion">Motion signal: <span id="nnMotionN"></span></label><input id="nnMotion" type="range" min="0" max="1" step=".1" value=".5"><label for="nnWeight">Light weight: <span id="nnWeightN"></span></label><input id="nnWeight" type="range" min="-2" max="2" step=".1" value="1"><label for="nnBias">Bias: <span id="nnBiasN"></span></label><input id="nnBias" type="range" min="-2" max="1" step=".1" value="-.4"><code id="nnFormula" class="formula"></code><div class="statrow"><div class="stat"><strong id="nnSum"></strong><small>Sum before ReLU</small></div><div class="stat"><strong id="nnOutput"></strong><small>Output activation</small></div></div><p>The motion weight stays at 0.8. Set a negative total to see ReLU turn off the output.</p>');
case'deepLearning':return intro('Peel back a feature hierarchy','<label for="dlPattern">Input pattern</label><select id="dlPattern"><option value="vertical">Vertical split</option><option value="horizontal">Horizontal split</option><option value="checker">Checkerboard</option><option value="blank">Blank field</option></select><label for="dlLayer">Inspect the representation</label><input id="dlLayer" type="range" min="0" max="4" value="0"><div class="flow-list" id="dlScores"></div><div class="callout" id="dlResult" aria-live="polite"></div><p>Exact calculations through a hand-built circuit. No weights are trained here, and scores are not probabilities.</p>');
case'matrixMath':return intro('Price two fruit baskets','<p>Quantities: A [2 apples, 1 orange]; B [1 apple, 3 oranges]. Prices use fictional units.</p><label for="matrixApple">Shop 1 apple price: <span id="matrixAppleN"></span></label><input id="matrixApple" type="range" min="1" max="6" step="1" value="3"><p>Shop 1 orange = 2. Shop 2 apple = 4, orange = 1.</p><div class="matrix-result" id="matrixCells" role="group" aria-label="Choose a basket and shop result"></div><code class="formula" id="matrixEquation"></code><p id="matrixExplanation" aria-live="polite"></p><button id="matrixNext" class="secondary">Trace the next result →</button>');
case'worldModel':return intro('Imagine, then compare with reality','<label for="wmAction">Repeat this action</label><select id="wmAction"><option value="1">Forward, one pulse</option><option value="0">Stay still</option><option value="-1">Backward, one pulse</option></select><label for="wmHorizon">Prediction horizon: <span id="wmHorizonN"></span> steps</label><input id="wmHorizon" type="range" min="1" max="6" value="3"><div class="statrow"><div class="stat"><strong id="wmScale"></strong><small>Model movement scale</small></div><div class="stat"><strong id="wmError"></strong><small>Endpoint error</small></div></div><button id="wmFit" class="primary">Fit the recorded transitions ↻</button><button id="wmReset" class="secondary">Restore an inaccurate model</button><div id="wmResult" class="callout" aria-live="polite"></div><p>Mint: imagined positions. Amber: observed positions. This deterministic environment has no noise; real environments and learned models are more complex.</p>');
}}
function bindLab(){
if($('#aiExample')){const f=()=>{example=$('#aiExample').value;const labels=example==='rule'?['AI','Explicit rules']:example==='classifier'?['AI','Machine learning','Classification']:['AI','Machine learning','Deep learning','Generation'];$('#aiMembership').innerHTML=labels.map(t=>`<span>${t}</span>`).join('');$('#aiExampleNote').textContent=example==='rule'?'A person writes: flag messages containing “claim a prize.” No model training is required for this rule.':example==='classifier'?'A linear classifier learns from labeled messages and predicts a spam label for a new message. Machine learning does not require a deep network.':'A Transformer language model uses learned patterns and the message context to draft a reply. This is deep learning used for a generative task.';setPart(example==='rule'?2:3)};$('#aiExample').value=example;$('#aiExample').onchange=f;f()}
if($('#mlTrain')){const f=()=>{const r=regression(w);$('#mlWeight').textContent=fmt(w);$('#mlLoss').textContent=r.loss.toFixed(4);$('#mlTest').innerHTML=`<strong>Held-out check · update ${steps}</strong>4 pulses → ${fmt(4*w)} predicted units. Actual: 8. Squared error: ${r.heldout.toFixed(4)}.`};$('#mlTrain').onclick=()=>{w=regression(w).next;steps++;f();setPart(3)};$('#mlReset').onclick=()=>{w=.4;steps=0;f();setPart(0)};f()}
if($('#nnLight')){const inputs=[['nnLight',light],['nnMotion',motion],['nnWeight',weight],['nnBias',bias]];const f=()=>{light=+$('#nnLight').value;motion=+$('#nnMotion').value;weight=+$('#nnWeight').value;bias=+$('#nnBias').value;inputs.forEach(([id])=>$('#'+id+'N').textContent=fmt(+$('#'+id).value));const v=nv();$('#nnFormula').textContent=`(${fmt(light)} × ${fmt(weight)}) + (${fmt(motion)} × 0.8) + (${fmt(bias)}) = ${fmt(v.z)}`;$('#nnSum').textContent=fmt(v.z);$('#nnOutput').textContent=fmt(v.a);};inputs.forEach(([id,v])=>{$('#'+id).value=v;$('#'+id).oninput=()=>{f();setPart(id==='nnWeight'?1:id==='nnBias'?2:0)}});f()}
if($('#dlPattern')){const f=()=>{pattern=$('#dlPattern').value;const v=fv();$('#dlScores').innerHTML=`<div>Left-right contrast <em>${fmt(v.scores[0])}</em></div><div>Up-down contrast <em>${fmt(v.scores[1])}</em></div>`;$('#dlResult').textContent=v.label;};$('#dlPattern').value=pattern;$('#dlPattern').onchange=()=>{f();setPart(0)};$('#dlLayer').oninput=()=>setPart(+$('#dlLayer').value);f()}
if($('#matrixApple')){const f=()=>{apple=+$('#matrixApple').value;$('#matrixAppleN').textContent=apple;const C=matrixProduct(A,B()),r=Math.floor(cell/2),c=cell%2;$('#matrixCells').innerHTML=C.flat().map((v,k)=>`<button data-matrix-cell="${k}" aria-pressed="${k===cell}" class="${k===cell?'chosen':''}"><small>Basket ${Math.floor(k/2)===0?'A':'B'} · Shop ${k%2+1}</small><strong>${v}</strong></button>`).join('');$('#matrixEquation').textContent=`[${A[r].join(', ')}] · [${B().map(row=>row[c]).join(', ')}] = ${A[r][0]}×${B()[0][c]} + ${A[r][1]}×${B()[1][c]} = ${C[r][c]}`;$('#matrixExplanation').textContent=`Row ${r+1} meets column ${c+1}. Total: ${C[r][c]} price units.`;$$('[data-matrix-cell]').forEach(b=>b.onclick=()=>{cell=+b.dataset.matrixCell;f();setPart(4)})};$('#matrixApple').value=apple;$('#matrixApple').oninput=()=>{f();setPart(1)};$('#matrixNext').onclick=()=>{cell=(cell+1)%4;f();setPart(2)};f()}
if($('#wmFit')){const f=()=>{action=+$('#wmAction').value;horizon=+$('#wmHorizon').value;const v=wv();$('#wmHorizonN').textContent=horizon;$('#wmScale').textContent=fmt(scale);$('#wmError').textContent=fmt(v.error);$('#wmResult').textContent=`Imagined endpoint ${fmt(v.predicted.at(-1))}; observed endpoint ${fmt(v.actual.at(-1))}. ${v.error<1e-8?'This toy rollout matches the environment.':'The movement-scale error accumulates over repeated steps.'}`};$('#wmAction').value=action;$('#wmHorizon').value=horizon;$('#wmAction').onchange=()=>{f();setPart(1)};$('#wmHorizon').oninput=()=>{f();setPart(3)};$('#wmFit').onclick=()=>{scale=fitDynamics();f();setPart(2)};$('#wmReset').onclick=()=>{scale=.7;f();setPart(5)};f()}
}
function payload(id,i){if(id===22)return i===0?'AI ⊃ ML ⊃ deep learning':i===2?'if phrase matches → flag':i===3?example==='generator'?'Transformer → draft reply':'linear classifier → label':undefined;
if(id===23)return ['x: 1,2,3; y: 2,4,6',`w = ${fmt(w)}`,`MSE = ${regression(w).loss.toFixed(4)}`,`gradient = ${fmt(regression(w).gradient)}`,`4 × ${fmt(w)} = ${fmt(4*w)}`,`weight after ${steps} updates`][i];
if(id===24){const v=nv();return [`x = [${fmt(light)}, ${fmt(motion)}]`,v.terms.map(fmt).join(' + '),`z = ${fmt(v.z)}`,`ReLU(${fmt(v.z)}) = ${fmt(v.a)}`,`activation = ${fmt(v.a)}`][i]}
if(id===25){const v=fv();return [pattern+' · 16 pixels','two directional contrast maps',v.scores.map(fmt).join(' / '),'compare feature averages',v.label][i]}
if(id===26){const r=Math.floor(cell/2),c=cell%2,ps=A[r].map((v,k)=>v*B()[k][c]);return [`row ${r+1}: [${A[r]}]`,`column ${c+1}: [${B().map(row=>row[c])}]`,ps.join(' + '),`total = ${ps[0]+ps[1]}`,`C[${r+1},${c+1}] = ${ps[0]+ps[1]}`][i]}
if(id===27){const v=wv();return ['(−1,−1.2), (1,1.2), (2,2.4)',`start 0; action ${action}`,`movement scale = ${fmt(scale)}`,v.predicted.map(fmt).join(' → '),`observed endpoint = ${fmt(v.actual.at(-1))}`,`absolute error = ${fmt(v.error)}`][i]}}
const C='#82e5b5',V='#b6a3ff',G='#f3bd71',blue='#82bfff';
function mesh(n,i,selected){const id=api.state().current;if(id<22)return false;const p=n.p,add=(v,size,c=C,a=.65)=>api.cube(p.map((x,k)=>x+v[k]),size,c,a),grid=(data,c,highlight=()=>true)=>data.forEach((row,r)=>row.forEach((v,k)=>add([(k-(row.length-1)/2)*.5,.55-r*.45,0],[.38,.3,.18+Math.abs(v)*.09],c,highlight(r,k)?(.25+.55*Math.min(1,Math.abs(v))):.12)));
switch(n.type){
case'family':[[3.2,2.5,2.2,C],[2.3,1.8,1.5,V],[1.3,1,.8,G]].forEach(([x,y,z,c])=>{for(const dx of [-1,1])for(const dz of [-1,1])add([dx*x/2,0,dz*z/2],[.035,y,.035],c,.65);for(const dy of [-1,1]){for(const dz of [-1,1])add([0,dy*y/2,dz*z/2],[x,.035,.035],c,.65);for(const dx of [-1,1])add([dx*x/2,dy*y/2,0],[.035,.035,z],c,.65)}});return true;
case'samples':trainingPairs.forEach(([x,y])=>add([(x-2)*.5,y*.12-.35,0],[.17,.17,.17],C));return true;
case'fit':for(let k=0;k<7;k++)add([-.8+k*.25,-.4+w*k*.09,0],[.08,.08,.08],V);return true;
case'holdout':add([0,.3,0],[.3,.3,.3],G);add([0,.3+(4*w-8)*.09,.3],[.14,.14,.14],V);return true;
case'signals':[light,motion].forEach((v,k)=>add([-.45+k*.9,v*.6-.3,0],[.3,Math.max(.03,v*1.2),.3],k?V:C));return true;
case'contributions':nv().terms.forEach((v,k)=>add([-.45+k*.9,v*.35,0],[.3,Math.max(.03,Math.abs(v)*.7),.3],v<0?G:k?V:C));return true;
case'bias':add([0,nv().z*.25,0],[.55,Math.max(.05,Math.abs(nv().z)*.5),.55],nv().z<0?G:C);return true;
case'relu':for(let k=0;k<12;k++){const x=-1+k*.18;add([x,Math.max(0,x)-.2,0],[.1,.07,.12],V)}add([Math.max(-1,Math.min(1,nv().z)),Math.max(0,Math.min(1,nv().z))-.2,0],[.18,.18,.18],G);return true;
case'pixels':grid(fv().grid,C);return true;
case'features':[[fv().dx,-.65,C],[fv().dy,.65,V]].forEach(([data,off,color])=>data.forEach((row,r)=>row.forEach((v,k)=>add([off+(k-(row.length-1)/2)*.22,.5-r*.24,0],[.17,.16,.15],color,.18+v*.65))));return true;
case'pooled':case'featureScores':fv().scores.forEach((v,k)=>add([-.45+k*.9,-.4+v*.65,0],[.4,Math.max(.03,v*1.3),.4],k?V:C));return true;
case'matrixA':grid(A,C,(r)=>r===Math.floor(cell/2));return true;
case'matrixB':grid(B(),V,(r,c)=>c===cell%2);return true;
case'matrixC':grid(matrixProduct(A,B()),G,(r,c)=>r*2+c===cell);return true;
case'products':{const r=Math.floor(cell/2),c=cell%2;A[r].forEach((v,k)=>add([-.45+k*.9,-.3+v*B()[k][c]*.04,0],[.4,v*B()[k][c]*.08,.4],k?V:C));return true}
case'sum':add([0,.1,0],[.7,.7,.7],G);return true;
case'output':add([0,.1,0],[.7,id===24?Math.max(.06,nv().a*.4):.5,.7],id===24&&nv().a===0?'#486171':C);return true;
case'transitions':grid(transitions,C);return true;
case'action':add([action*.6,0,0],[.35,.35,.35],G);return true;
case'dynamics':for(let k=0;k<4;k++)add([-.6+k*.4,scale*k*.15,0],[.16,.16,.16],V);return true;
case'rollout':case'reality':{const path=n.type==='rollout'?wv().predicted:wv().actual;path.forEach((v,k)=>add([v*.16,-.2+k*.07,k*.18-.5],[.16,.16,.16],n.type==='rollout'?C:G));return true}
case'discrepancy':[wv().predicted.at(-1),wv().actual.at(-1)].forEach((v,k)=>add([-.4+k*.8,v*.1,0],[.3,.12,.3],k?G:C));return true;
}return false;}
function ornaments(n,i,selected){const st=api.state();if(st.current<22)return;const p=n.p,text=(v,s,c=C)=>{const q=api.project(p.map((x,k)=>x+v[k]));st.ctx.save();st.ctx.font='600 14px monospace';st.ctx.textAlign='center';st.ctx.fillStyle=c;st.ctx.fillText(s,q[0],q[1]);st.ctx.restore()};const line=(a,b,c=C)=>api.line3(p.map((x,k)=>x+a[k]),p.map((x,k)=>x+b[k]),c,1.3,.7);
if(n.type==='family'){text([0,1.65,0],'AI',C);text([0,.95,0],'ML',V);text([0,.32,0],'DEEP',G)}
if(n.type==='samples'||n.type==='fit'||n.type==='holdout'){line([-1,-.55,0],[1,-.55,0],blue);line([-1,-.55,0],[-1,1.2,0],blue);if(n.type==='fit')line([-.8,-.4,0],[.7,-.4+w*.54,0],V)}
if(['matrixA','matrixB','matrixC'].includes(n.type)){const d=n.type==='matrixA'?A:n.type==='matrixB'?B():matrixProduct(A,B());d.forEach((row,r)=>row.forEach((v,c)=>text([(c-.5)*.5,.65-r*.45,.22],String(v),'#effff8')))}
if(st.current===24&&['signals','contributions','bias','output'].includes(n.type)){const vals=n.type==='signals'?[light,motion]:n.type==='contributions'?nv().terms:n.type==='bias'?[nv().z]:[nv().a];vals.forEach((v,k)=>text([vals.length===1?0:-.45+k*.9,1.1,0],fmt(v),v<0?G:C));}
if(n.type==='features'){text([-.65,.95,0],'L/R',C);text([.65,.95,0],'U/D',V)}
if(n.type==='pooled'||n.type==='featureScores')fv().scores.forEach((v,k)=>text([-.45+k*.9,1.2,0],fmt(v),k?V:C));
if(n.type==='products'){const r=Math.floor(cell/2),c=cell%2;A[r].forEach((v,k)=>text([-.45+k*.9,1.3,0],String(v*B()[k][c]),k?V:C))}
if(n.type==='sum')text([0,.8,0],String(matrixProduct(A,B())[Math.floor(cell/2)][cell%2]),G);
if(n.type==='rollout'||n.type==='reality'){const arr=n.type==='rollout'?wv().predicted:wv().actual;for(let k=1;k<arr.length;k++)line([arr[k-1]*.16,-.2+(k-1)*.07,(k-1)*.18-.5],[arr[k]*.16,-.2+k*.07,k*.18-.5],n.type==='rollout'?C:G);text([0,1.15,0],fmt(arr.at(-1)),n.type==='rollout'?C:G)}
}
return {labHTML,bindLab,payload,mesh,ornaments};
}
